---
permalink: windows/concept-prerequisites-for-data-protection.html 
sidebar: sidebar 
keywords: aware, consideration, perform, data, protection 
summary: 'È necessario conoscere alcune considerazioni per l"esecuzione della protezione dei dati.' 
---
= Considerazioni per l'esecuzione della protezione dei dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere alcune considerazioni per l'esecuzione della protezione dei dati.

* Per eseguire operazioni di cloning o ripristino da sistemi secondari, è necessario montare il volume di destinazione nello spazio dei nomi ed esportarlo correttamente.
* È necessario disattivare il parametro di configurazione SnapDrive `check-export-permission-nfs-clone` impostando il valore su *off*.
+
La documentazione di SnapDrive per UNIX sul sito del supporto NetApp contiene informazioni aggiuntive su `check-export-permission-nfs-clone parameter`.

* È necessario configurare la relazione di SnapMirror per i volumi di storage secondari richiesti nel sistema di storage secondario.
* È necessario configurare la relazione SnapVault per i qtree dello storage secondario richiesti nel sistema di storage secondario per Data ONTAP che opera in 7-Mode.
* È necessario definire un criterio e regole per l'etichetta SnapMirror definita dall'utente se si utilizza SnapVault post-script per Clustered Data ONTAP.
+
SnapVault post-script supporta i volumi Data ONTAP in cluster e i tipi di relazione SnapMirror DP e XDP. La documentazione di ONTAP sul sito del supporto NetApp contiene informazioni sulla configurazione di SnapMirror e SnapVault.



http://mysupport.netapp.com/["Documentazione sul sito di supporto NetApp"^]
