---
permalink: windows/concept-collecting-additional-log-information-for-easier-debugging.html 
sidebar: sidebar 
keywords: additional, log, debug, fail, snapmanager, operation, external, environment, variable, server.log.level, file, collect 
summary: 'Se sono necessari log aggiuntivi per eseguire il debug di un"operazione SnapManager non riuscita, è necessario impostare una variabile di ambiente esterna server.log.level. Questa variabile sovrascrive il livello di log predefinito e scarica tutti i messaggi di log nel file di log. Ad esempio, è possibile modificare il livello di log in DEBUG, che registra messaggi aggiuntivi e può aiutare a risolvere i problemi di debug.' 
---
= Raccolta di informazioni aggiuntive sui log per semplificare il debugging
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se sono necessari log aggiuntivi per eseguire il debug di un'operazione SnapManager non riuscita, è necessario impostare una variabile di ambiente esterna `server.log.level`. Questa variabile sovrascrive il livello di log predefinito e scarica tutti i messaggi di log nel file di log. Ad esempio, è possibile modificare il livello di log in DEBUG, che registra messaggi aggiuntivi e può aiutare a risolvere i problemi di debug.

I registri SnapManager sono disponibili nelle seguenti posizioni:

* `SnapManager_install_directory\log`


Per eseguire l'override del livello di registro predefinito, attenersi alla seguente procedura:

. Creare un `platform.override` File di testo nella directory di installazione di SnapManager.
. Aggiungere il `server.log.level` nel `platform.override` file di testo.
. Assegnare un valore (*_TRACE, DEBUG, INFO, WARN, ERROR, FATAL (O PROGRESS_*) al `server.log.level` parametro.
+
Ad esempio, per modificare il livello di log in _ERROR_, impostare il valore di `server.log.level` A _ERRORE_.

+
`server.log.level=ERROR`

. Riavviare il server SnapManager.



NOTE: Se le informazioni aggiuntive del registro non sono richieste, è possibile eliminare `server.log.level` dal `platform.override` file di testo.

SnapManager gestisce il volume dei file di log del server in base ai valori definiti dall'utente dei seguenti parametri in `smsap.config` file:

* `log.max_log_files`
* `log.max_log_file_size`
* `log.max_rolling_operation_factory_logs`

