---
permalink: windows/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, user, allow, resource, repository, repositories, host, profile, credential, management 
summary: 'È possibile gestire la sicurezza in SnapManager applicando l"autenticazione dell"utente. Il metodo di autenticazione dell"utente consente di accedere a risorse come repository, host e profili.' 
---
= Sicurezza e gestione delle credenziali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire la sicurezza in SnapManager applicando l'autenticazione dell'utente. Il metodo di autenticazione dell'utente consente di accedere a risorse come repository, host e profili.

Quando si esegue un'operazione utilizzando l'interfaccia della riga di comando (CLI) o l'interfaccia utente grafica (GUI), SnapManager recupera il set di credenziali per repository e profili. SnapManager salva le credenziali delle installazioni precedenti.

Il repository e i profili possono essere protetti con una password. Una credenziale è la password configurata per l'utente per un oggetto e la password non è configurata sull'oggetto stesso.

È possibile gestire l'autenticazione e le credenziali eseguendo le seguenti operazioni:

* Gestire l'autenticazione dell'utente tramite richieste di password sulle operazioni o utilizzando `smsap credential set` comando.
+
Impostare le credenziali per un repository, un host o un profilo.

* Visualizzare le credenziali che regolano le risorse a cui si ha accesso.
* Cancellare le credenziali di un utente per tutte le risorse (host, repository e profili).
* Eliminare le credenziali di un utente per le singole risorse (host, repository e profili).



NOTE: Se il database del repository si trova su un host Windows, l'utente locale o amministratore e l'utente di dominio devono disporre delle stesse credenziali.
