---
permalink: windows/reference-the-smosmsapclone-show-command.html 
sidebar: sidebar 
keywords: run, clone, show, command, display, information, database, profile, smsap 
summary: È possibile eseguire il comando clone show per visualizzare le informazioni sui cloni del database per il profilo specificato. 
---
= Il comando ssap clone show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire `clone show` per visualizzare le informazioni sui cloni del database per il profilo specificato.



== Sintassi

[listing]
----

smsap clone show
-profile profile_name
[-id  guid | -label clone_name]
[-quiet | -verbose]
----


== Parametri

* *`-profile _profile_name_`*
+
Specifica l'elenco dei cloni associati al profilo. Il profilo contiene l'identificatore del database e altre informazioni del database.

* *`-id _guid_`*
+
Mostra le informazioni sul clone con il GUID specificato. Il GUID viene generato da SnapManager quando si crea un clone. È possibile utilizzare `smsap clone show` Per visualizzare il GUID per ciascun clone.

* *`-label _label_name_`*
+
Mostra le informazioni sul clone con l'etichetta specificata.

* *`-quiet`*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *`-verbose`*
+
Visualizza messaggi di errore, di avviso e informativi nella console.





== Esempio

Nell'esempio seguente vengono visualizzate informazioni sul clone:

[listing]
----
smsap clone show -profile SALES1 -label full_backup_sales_May -verbose
----
Il seguente output mostra informazioni su un clone di un backup sullo storage primario:

[listing]
----
Clone id: 8abc013111b916e30111b916ffb40001
Clone status: SUCCESS
Clone SID: hsdbc
Clone label: hsdbc
Clone comment: null
Clone start time: 2007-04-03 16:15:50
Clone end time: 2007-04-03 16:18:17
Clone host: Host1
Filesystem: E:\ssys1\data_clone\
File: E:\ssys1\data_clone\hsdb\sysaux01.dbf
File: E:\ssys1\data_clone\hsdb\undotbs01.dbf
File: E:\ssys1\data_clone\hsdb\users01.dbf
File: E:\ssys1\data_clone\hsdb\system01.dbf
File: E:\ssys1\data_clone\hsdb\undotbs02.dbf
Backup id: 8abc013111a450480111a45066210001
Backup label: full_backup_sales_May
Backup SID: hsdb1
Backup comment:
Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Backup host: server1
----