---
permalink: windows/reference-the-smosmsap-password-reset-command.html 
sidebar: sidebar 
keywords: run, password, reset, command, profile, smsap 
summary: È possibile eseguire il comando di reimpostazione della password per reimpostare la password di un profilo. 
---
= Il comando di ripristino della password di smsap
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire la password `reset command` per reimpostare la password di un profilo.



== Sintassi

[listing]
----

smsap password reset
-profile profile
[-profile-password profile_password]
[-repository-hostadmin-password repository_hostadmin_password]
[-quiet | -verbose]
----


== Parametri

* *`-profile _profile_`*
+
Specifica il nome del profilo per cui si desidera reimpostare la password.

* *`-profile-password _profile_password_`*
+
Specifica la nuova password per il profilo.

* *`-repository-hostadmin-password _admin_password_`*
+
Specifica la credenziale dell'utente autorizzato con privilegio di amministratore locale per il database del repository.

* *`-quiet`*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *`-verbose`*
+
Visualizza messaggi di errore, di avviso e informativi nella console.


