---
permalink: windows/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credential, user, access, secure, resource, host, repository, repositories, database, profile, password, snapmanager, option, smsap 
summary: 'Questo comando consente di impostare le credenziali per consentire agli utenti di accedere a risorse sicure, come host, repository e profili di database. La password host è la password dell"utente sull"host su cui è in esecuzione SnapManager. La password del repository è la password dell"utente Oracle che contiene lo schema del repository SnapManager. La password del profilo è una password creata dalla persona che crea il profilo. Per le opzioni host e repository, se l"opzione -password opzionale non è inclusa, verrà richiesto di inserire una password del tipo specificato negli argomenti del comando.' 
---
= Il comando sspap credential set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando consente di impostare le credenziali per consentire agli utenti di accedere a risorse sicure, come host, repository e profili di database. La password host è la password dell'utente sull'host su cui è in esecuzione SnapManager. La password del repository è la password dell'utente Oracle che contiene lo schema del repository SnapManager. La password del profilo è una password creata dalla persona che crea il profilo. Per le opzioni host e repository, se opzionale `-password` opzione non inclusa, verrà richiesto di inserire una password del tipo specificato negli argomenti del comando.



== Sintassi

[listing]
----

smsap credential set
[-host
-name host_name
-username username]
[-password password]] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username] [-password repo_password]]
-port repo_port |
[-profile
-name profile_name]
[-password password]]
[-quiet | -verbose]
----


== Parametri

* *`-host _hostname_`*
+
Specifica il nome o l'indirizzo IP del server host su cui è in esecuzione SnapManager.

+
Il `-host` il parametro include le seguenti opzioni:

+
** `-name host_name`: Specifica il nome dell'host per il quale si desidera impostare la password.
** `-username user_name`: Specifica il nome utente sull'host.
** `-password password`: Specifica la password dell'utente sull'host.


* *`-repository -dbname`*
+
Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.

+
Il `-repository` il parametro include le seguenti opzioni:

+
** `-dbnamerepo_service_name`: Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.
** `-host repo_host`: Specifica il nome o l'indirizzo IP del server host su cui viene eseguito il database del repository.
** `-login-username repo_username`: Specifica il nome utente necessario per accedere al database in cui è memorizzato il repository.
** `-password password`: Specifica la password necessaria per accedere al database che memorizza il repository.
** `-port repo_port`: Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.


* *`-profile -name _profile_name_`*
+
Specifica il profilo a cui è associato il database.

+
Il `-profile` il parametro include la seguente opzione:

+
** `-name profilename`: Specifica il nome del profilo per il quale si desidera impostare la password.
** `-password password`: Specifica la password necessaria per accedere al profilo.


* *`-quiet`*
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *`-verbose`*
+
Visualizza messaggi di errore, di avviso e informativi sulla console.





== Esempio di comando per l'impostazione delle credenziali del repository

Nell'esempio seguente vengono impostate le credenziali per un repository.

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== Esempio di comando per l'impostazione delle credenziali dell'host

Poiché una credenziale host rappresenta una credenziale effettiva del sistema operativo, deve includere il nome utente oltre alla password.

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----