---
permalink: windows/reference-the-smosmsapcredential-delete-command.html 
sidebar: sidebar 
keywords: command, delete, user, credential, particular, secure, resource, smsap 
summary: 'Questo comando elimina le credenziali dell"utente per una particolare risorsa protetta.' 
---
= Il comando di eliminazione delle credenziali smsap
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando elimina le credenziali dell'utente per una particolare risorsa protetta.



== Sintassi

[listing]
----

smsap credential delete
[-host -name host_name
-username username] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port] |
[-profile
-name profile_name]
[-quiet | -verbose]
----


== Parametri

* *`-host _hostname_`*
+
Specifica il nome del server host su cui è in esecuzione SnapManager.

+
Il `-host` il parametro include le seguenti opzioni:

+
** `-name host_name`Specifica il nome dell'host per il quale si desidera eliminare la password.
** `-username user_name`: Specifica il nome utente sull'host.


* *`-repository -dbname`*
+
Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.

+
Il `-repository` il parametro include le seguenti opzioni:

+
** `-dbnamerepo_service_name`: Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.
** `-host repo_host`: Specifica il nome o l'indirizzo IP del server host su cui viene eseguito il database del repository.
** `-login-username repo_username`: Specifica il nome utente necessario per accedere al database in cui è memorizzato il repository.
** `-port repo_port`: Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.


* *`-profile -name _profile_name_`*
+
Specifica il profilo a cui è associato il database.

+
Il `-profile` il parametro include la seguente opzione:

+
** `-name _profilename_`: Specifica il nome del profilo per cui si desidera eliminare la password.


* *`-quiet`*
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *`-verbose`*
+
Visualizza messaggi di errore, di avviso e informativi sulla console.





== Esempio di comando

Questo esempio elimina le credenziali del profilo.

[listing]
----
smsap credential delete -profile -name user1 -verbose
----
[listing]
----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
Questo esempio elimina le credenziali del repository.

[listing]
----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
Questo esempio elimina le credenziali dell'host.

[listing]
----
smsap credential delete -host -name Host2
----
[listing]
----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----