---
permalink: windows/task-configuring-history-for-backup-operation.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, maintain, history, operation, cli, gui, history, operation, report, configure, configuring 
summary: 'SnapManager per SAP consente di mantenere la cronologia delle operazioni SnapManager dalla CLI o dall"interfaccia grafica utente di SnapManager. È possibile visualizzare la cronologia dell"operazione SnapManager come report.' 
---
= Configurazione della cronologia per il funzionamento di SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager per SAP consente di mantenere la cronologia delle operazioni SnapManager dalla CLI o dall'interfaccia grafica utente di SnapManager. È possibile visualizzare la cronologia dell'operazione SnapManager come report.

.Fase
. Per configurare la cronologia delle operazioni SnapManager, immettere il seguente comando:
+
`smsap history set -profile {-name, profile_name [profile_name1, profile_name2] | -all-repository-login [-passwordrepo_password] -usernamerepo_username-dbnamerepo_dbname-hostrepo_host-portrepo_port} -operation {-operationsoperation_name [operation_name1, operation_name2] | -all} -retain {-countretain_count | -dailyretain_daily | -weeklyretain_weekly | -monthlyretain_monthly} [-quiet | -verbose]`



[listing]
----

smsap
history set -profile -name PROFILE1 -operation -operations backup -retain -daily 6 -verbose
----
[listing]
----

smsap
history set -profile -name PROFILE1 -operation -all -retain -weekly 3 -verbose
----