---
permalink: windows/task-installing-snapmanager-for-oracle-snapmanager-for-sap.html 
sidebar: sidebar 
keywords: install, snapmanager, host, database, manage, instance, host, sap 
summary: 'È possibile installare SnapManager sull"host che dispone di uno o più database da gestire. È possibile installare una sola istanza di SnapManager per host.' 
---
= Installazione di SnapManager per SAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile installare SnapManager sull'host che dispone di uno o più database da gestire. È possibile installare una sola istanza di SnapManager per host.

* È necessario aver completato le attività di preinstallazione richieste.
* È necessario scaricare l'ultima versione del pacchetto di installazione di SnapManager.
* La versione appropriata di SnapDrive per Windows deve essere installata e configurata su tutti gli host di destinazione.
+
Per informazioni sull'installazione e la configurazione di SnapDrive per Windows, consultare la _Guida amministrativa e d'installazione di SnapDrive per Windows_.

+
.. Fare doppio clic sul file di installazione di SnapManager:
+
|===
| Se il sistema operativo è... | Quindi utilizzare... 


 a| 
Windows x86
 a| 
netapp.smsap.windows-x86-version.exe



 a| 
Windows x64
 a| 
netapp.smsap.windows-x64-version.exe

|===
+
Viene visualizzato il seguente messaggio: Impossibile verificare l'editore. Eseguire questo software?

.. Fare clic su *OK*.
.. Nella finestra Introduzione, fare clic su *Avanti*.
.. Nella finestra Choose Install Folder (Scegli cartella di installazione), fare clic su *Next* (Avanti) per accettare la posizione di installazione predefinita o selezionare una nuova posizione.
+
Il percorso predefinito è: C: File di programma NetApp SnapManager per SAP.

.. Nella finestra Menu Availability (disponibilità menu), fare clic su *Next* (Avanti).
.. Nella finestra Specify Service Properties (specifica proprietà del servizio), immettere le informazioni relative all'account e alla password per il servizio Windows.
+
L'account specificato deve essere membro dei seguenti gruppi:

+
*** Il gruppo di amministrazione locale del sistema di storage
*** Il gruppo dell'amministratore locale
*** Il gruppo ora_DBA è possibile specificare se il servizio deve essere avviato automaticamente dopo il riavvio o manualmente.


.. Nella finestra Pre-Installation Summary (Riepilogo preinstallazione), fare clic su *Install* (Installa).
.. Nella finestra Installazione completata, fare clic su *Avanti*.
.. Nella finestra informazioni importanti, fare clic su *fine* per uscire dal programma di installazione.




Una volta completata l'installazione, è possibile verificare che l'installazione sia stata eseguita correttamente:

. Avviare il server SnapManager:
+
.. Nella finestra servizi Windows, selezionare *versione di NetApp SnapManager per SAP*.
.. Nel pannello di sinistra, fare clic su *Start*.


. Verificare che il sistema SnapManager funzioni correttamente:
+
.. Fare clic su *Start* > *programmi* > *NetApp* > *SnapManager per SAP* > *Avvia interfaccia riga di comando SMSAP (CLI)*.
.. Nell'interfaccia della riga di comando (CLI), immettere il seguente comando: `smsap system verify`Viene visualizzato il seguente messaggio: Operation ID number successed (numero ID operazione riuscita).


+
Number è il numero ID dell'operazione.



*Informazioni correlate*

xref:concept-preparing-to-install-snapmanager-for-oraclesnapmanager-for-sap.adoc[Preparazione all'installazione di SnapManager per SAP]

xref:concept-preinstallation-tasks.adoc[Attività di preinstallazione]

xref:task-downloading-snapmanager-for-oraclesnapmanager-for-sap-installation-package.adoc[Download del pacchetto di installazione di SnapManager per SAP]

http://mysupport.netapp.com/["Documentazione sul sito di supporto NetApp: mysupport.netapp.com"]
