---
permalink: windows/task-restoring-backups-on-primary-storage.html 
sidebar: sidebar 
keywords: backup, restore, command, database, primary, storage, restoring 
summary: È possibile utilizzare il comando di ripristino del backup per ripristinare un backup del database sullo storage primario. 
---
= Ripristino dei backup sullo storage primario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il comando di ripristino del backup per ripristinare un backup del database sullo storage primario.

È possibile utilizzare le opzioni del comando di ripristino del backup per specificare se SnapManager deve ripristinare tutto o parte del backup. SnapManager consente inoltre di ripristinare i file di controllo insieme ai file di dati o agli spazi delle tabelle dai backup in un'operazione con un singolo utente. È possibile includere -controlfile with -complete per ripristinare i file di controllo insieme a tablespace e file di dati.

È possibile selezionare una delle seguenti opzioni per ripristinare il backup:

[cols="1a,1a"]
|===
| Se si desidera ripristinare... | Utilizzare... 


 a| 
L'intero backup con tutti i tablespace e i file di dati
 a| 
-completo



 a| 
L'elenco di tablespace specifici
 a| 
-tablespaces



 a| 
File di dati specifici
 a| 
-file



 a| 
Solo i file di controllo
 a| 
-controlfiles



 a| 
Tablespace, file di dati e file di controllo
 a| 
-complete -controlfiles

|===
È anche possibile ripristinare il backup da una posizione alternativa specificando -restorespec.

Se si include -recover, è possibile ripristinare il database per:

* L'ultima transazione che si è verificata nel database (tutti i registri)
* Data e ora specifiche
* Un numero SCN (System Change Number) Oracle specifico
* L'ora del backup (nessun registro)
* Solo ripristino



NOTE: Sia il ripristino di data e ora che il ripristino SCN sono ripristini point-in-time.

SnapManager (3.2 o versione successiva) consente di ripristinare automaticamente i backup del database ripristinati utilizzando i file di registro dell'archivio. Anche se i file di log dell'archivio sono disponibili nella posizione esterna, se si specifica l'opzione -recover-from-location, SnapManager utilizza i file di log dell'archivio dalla posizione esterna per ripristinare i backup del database ripristinati.

Quando si specificano le posizioni del registro di archiviazione esterno per il ripristino dei backup ripristinati, è necessario includere i nomi delle posizioni esterne in maiuscolo. Nel file system, tutti i nomi delle cartelle e delle sottocartelle devono essere in maiuscolo, perché Oracle converte il percorso di destinazione in maiuscolo e prevede che i percorsi di destinazione esterni, i nomi delle cartelle e i nomi delle sottocartelle siano in maiuscolo. Se si specificano i percorsi di destinazione del log di archiviazione esterno in minuscolo, Oracle potrebbe non essere in grado di identificare il percorso specificato e non riuscire a ripristinare il database.

SnapManager fornisce la posizione esterna a Oracle. Tuttavia, Oracle non identifica i file dalla destinazione esterna. Questo comportamento si verifica nella destinazione dell'area di ripristino flash. Si tratta di problemi con Oracle e la soluzione è avere sempre il backup dei file di log dell'archivio in tali layout di database.

Se viene fornita una data o un numero SCN incoerente, il ripristino si interrompe all'ultimo punto coerente recuperato con il messaggio di errore Recovery successed (Ripristino riuscito), ma insufficiente. È necessario eseguire manualmente il ripristino in uno stato coerente.

Per il ripristino quando non vengono applicati registri, SnapManager esegue il ripristino fino all'ultimo numero di configurazione del file di registro dell'archivio creato durante il backup. Se il database è coerente fino a quando non viene visualizzato questo SCN, il database viene aperto correttamente. Se a questo punto il database non è coerente, SnapManager tenta comunque di aprire il database, che verrà aperto correttamente, se il database è già coerente.


NOTE: SnapManager non supporta il ripristino dei backup solo log dell'archivio.

Se la destinazione del registro di archiviazione non è uno storage con funzionalità Snapshot, SnapManager consente di ripristinare i backup del database ripristinati utilizzando il profilo. Prima di eseguire operazioni SnapManager su storage non Snapshot, aggiungere le destinazioni per archiviLogs.exclude in sspap.config.

Prima di creare un profilo, è necessario impostare il parametro exclude. Solo dopo aver impostato il parametro exclude nel file di configurazione SnapManager, la creazione del profilo ha esito positivo.

Se il backup è già stato montato, SnapManager non lo installa di nuovo e utilizza il backup già montato. Se il backup viene montato da un altro utente e l'utente corrente non ha accesso al backup precedentemente montato, gli altri utenti devono fornire le autorizzazioni. Tutti i file di log dell'archivio dispongono dei permessi di lettura per i proprietari dei gruppi; l'utente corrente potrebbe non ottenere i permessi, se il backup viene montato da un gruppo di utenti diverso. Gli utenti possono assegnare manualmente i permessi ai file di registro dell'archivio montati e riprovare il ripristino o il ripristino.

È possibile specificare l'opzione -dump come parametro facoltativo per raccogliere i file dump dopo l'operazione di ripristino riuscita o non riuscita.

. Immettere il seguente comando:
+
`smsap backup restore -profileprofile_name-labellabel-complete-recover -alllogs [-recover-from-locationpath [,path2]]-dump-verbose`

+
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 - complete -recover -alllogs -verbose`

. Per ripristinare i dati per diversi scenari, completare una delle seguenti operazioni:
+
[cols="1a,1a"]
|===
| Se si desidera ripristinare... | Esempio di comando 


 a| 
Database completo senza file di controllo e ripristino a un numero SCN specifico (3794392). In questo caso, i file di controllo correnti esistono, ma tutti i file di dati vengono danneggiati o persi. Ripristinare e ripristinare il database da un backup online completo esistente a un punto immediatamente precedente a quello SCN.
 a| 
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 -complete -recover -until 3794392 -verbose`



 a| 
Database completo senza file di controllo e ripristino fino a data e ora.
 a| 
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 -complete -recover -until 2008-09-15:15:29:23 -verbose`



 a| 
Database completo senza file di controllo e ripristino fino a dati e tempi. In questo caso, i file di controllo correnti esistono, ma tutti i file di dati vengono danneggiati o persi oppure si è verificato un errore logico dopo un determinato periodo di tempo. Ripristinare e ripristinare il database da un backup online completo esistente a una data e un'ora immediatamente prima del punto di errore.
 a| 
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 -complete -recover -until "2008-09-15:15:29:23" -verbose`



 a| 
Database parziale (uno o più file di dati) senza file di controllo e ripristino utilizzando tutti i registri disponibili. In questo caso, esistono i file di controllo correnti, ma uno o più file di dati vengono danneggiati o persi. Ripristinare questi file di dati e ripristinare il database da un backup online completo esistente utilizzando tutti i registri disponibili.
 a| 
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 -files E:\disks\s02.dbf E:\disks\sales03.dbf E:\disks\sales04.dbf -recover -alllogs -verbose`



 a| 
Database parziale (uno o più spazi delle tabelle) senza file di controllo e ripristino utilizzando tutti i registri disponibili. In questo caso, esistono i file di controllo correnti, ma uno o più tablespace vengono eliminati o uno o più file di dati appartenenti allo spazio di tabella vengono danneggiati o persi. Ripristinare questi spazi delle tabelle e ripristinare il database da un backup online completo esistente utilizzando tutti i registri disponibili.
 a| 
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 -tablespaces users -recover -alllogs -verbose`



 a| 
Controllare solo i file e ripristinare utilizzando tutti i registri disponibili. In questo caso, i file di dati esistono, ma tutti i file di controllo vengono danneggiati o persi. Ripristinare solo i file di controllo e ripristinare il database da un backup online completo esistente utilizzando tutti i registri disponibili.
 a| 
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 -controlfiles -recover -alllogs -verbose`



 a| 
Database completo senza file di controllo e ripristino utilizzando i file di controllo di backup e tutti i registri disponibili. In questo caso, tutti i file di dati vengono danneggiati o persi. Ripristinare solo i file di controllo e ripristinare il database da un backup online completo esistente utilizzando tutti i registri disponibili.
 a| 
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 -complete -using-backup-controlfile -recover -alllogs -verbose`



 a| 
Ripristinare il database ripristinato utilizzando i file di log dell'archivio dalla posizione del log dell'archivio esterno.
 a| 
`smsap backup restore -profile targetdb1_prof1 -label full_bkup_sales_nov_08 -complete -using-backup-controlfile -recover -alllogs -recover-from-location E:\\archive -verbose`

|===
. Specificare le posizioni esterne del log di archiviazione utilizzando l'opzione -recover-from-location.


*Informazioni correlate*

xref:task-restoring-backups-from-an-alternate-location.adoc[Ripristino dei backup da una posizione alternativa]

xref:reference-the-smosmsapbackup-restore-command.adoc[Il comando di ripristino del backup di smsap]
