---
permalink: windows/task-starting-the-snapmanager-graphical-user-interface.html 
sidebar: sidebar 
keywords: snapmanager, install, host, graphical, user, interface, gui, list, program, start 
summary: 'Se SnapManager è installato sull"host, avviare l"interfaccia grafica utente per SnapManager selezionando il programma da un elenco di programmi.' 
---
= Avvio dell'interfaccia grafica di SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se SnapManager è installato sull'host, avviare l'interfaccia grafica utente (GUI) per SnapManager selezionando il programma da un elenco di programmi.

* Assicurarsi che il server SnapManager sia avviato.


È possibile avviare l'interfaccia grafica di SnapManager in uno dei seguenti modi:

* Nell'host SnapManager, fare clic su *Start* > *tutti i programmi* > *NetApp* > *SnapManager per SAP* > *Avvia l'interfaccia grafica di SMSAP*.
* Se SnapManager non è installato sull'host, utilizzare Java Web Start, che scarica i componenti SnapManager e avvia la GUI.


*Informazioni correlate*

xref:task-downloading-and-starting-the-graphical-user-interface-using-java-web-start-windows.adoc[Scaricare e avviare l'interfaccia grafica utente utilizzando Java Web Start]
