---
permalink: windows/task-customizing-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, cusomtizing 
summary: 'È possibile personalizzare l"oggetto dell"e-mail per il nuovo profilo al momento della creazione.' 
---
= Personalizzazione dell'oggetto dell'e-mail per un nuovo profilo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile personalizzare l'oggetto dell'e-mail per il nuovo profilo al momento della creazione.

Puoi personalizzare l'oggetto dell'email usando il modello{profile}_{nome-operazione}_{db-sid}_{db-host}_{data-inizio}_{data-fine}_{stato} o inserisci il tuo testo.

|===
| Nome della variabile | Descrizione | Valore di esempio 


 a| 
profilo
 a| 
Nome del profilo utilizzato per l'operazione del database
 a| 
PROF1



 a| 
nome-operazione
 a| 
Nome operazione database
 a| 
Backup, backup dei dati, backup dei dati e dei registri di archiviazione



 a| 
db-sid
 a| 
SID del database
 a| 
DB1



 a| 
db-host
 a| 
Nome del server host
 a| 
Host



 a| 
data di inizio
 a| 
Ora di inizio dell'operazione del database nel formato mmdd:hh:ss yyyy
 a| 
Aprile 27 21:00:45 PST 2012



 a| 
data di fine
 a| 
Ora di fine dell'operazione del database nel formato mmdd:hh:ss yyyy
 a| 
Aprile 27 21:10:45 PST 2012



 a| 
stato
 a| 
Stato operativo del database
 a| 
Successo

|===
Se non si fornisce alcun valore per le variabili, SnapManager visualizza il seguente messaggio di errore: Valori mancanti -subject.

. Immettere il seguente comando:
+
`smsap profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][ [ ]] [-notification [-success-emailemail_address1,email_address2-subjectsubject_pattern] [-failure-emailemail_address1,email_address2-subjectsubject_pattern]]`


