---
permalink: windows/task-mounting-backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, host, available, scenario, tools, oracle, recovery, manager, rman, file 
summary: 'SnapManager gestisce automaticamente il montaggio di un backup per renderlo disponibile all"host. È inoltre possibile montare i backup in scenari in cui si utilizza un tool esterno, ad esempio Oracle Recovery Manager (RMAN), per accedere ai file nel backup.' 
---
= Montaggio dei backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager gestisce automaticamente il montaggio di un backup per renderlo disponibile all'host. È inoltre possibile montare i backup in scenari in cui si utilizza uno strumento esterno, ad esempio Oracle Recovery Manager (RMAN), per accedere ai file nel backup.

Il comando smsap backup mount visualizza un elenco di percorsi in cui sono state montate le copie Snapshot costituite dal backup.


NOTE: È possibile raccogliere i file dump dopo un'operazione di montaggio di backup riuscita o non riuscita.

. Per attivare un backup, immettere il seguente comando:
+
`smsap backup mount -profile profile_name label [data | -archivelogs] | -id id} [-host-host] [-dump] [-quiet | -verbose]`



*Informazioni correlate*

xref:reference-the-smosmsapbackup-mount-command.adoc[Il comando smsap backup mount]
