---
permalink: windows/task-setting-credentials-after-clearing-credential-cache.html 
sidebar: sidebar 
keywords: clear, cache, remove, store, user, credential, host, repository, repositories, profile, set 
summary: Dopo aver cancellato la cache per rimuovere le credenziali utente memorizzate, è possibile impostare le credenziali per gli host, i repository e i profili. 
---
= Impostazione delle credenziali dopo la cancellazione della cache delle credenziali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver cancellato la cache per rimuovere le credenziali utente memorizzate, è possibile impostare le credenziali per gli host, i repository e i profili.

È necessario assicurarsi di impostare le stesse credenziali utente per il repository, l'host del profilo e il profilo forniti in precedenza. Durante l'impostazione delle credenziali utente viene creato un file di credenziali crittografato.

Il file delle credenziali si trova in C:/documenti e impostazioni/Amministratore/dati applicazioni/NetApp/SSMAP/3.3.0.

Dall'interfaccia grafica utente (GUI) di SnapManager, se non è presente alcun repository in Repository, attenersi alla seguente procedura:

. Fare clic su *Tasks* > *Add Existing Repository* (Aggiungi repository esistente) per aggiungere un repository esistente.
. Per impostare le credenziali per il repository, attenersi alla seguente procedura:
+
.. Fare clic con il pulsante destro del mouse sul repository e selezionare *Apri*.
.. Nella finestra Repository Credentials Authentication (autenticazione credenziali repository), immettere le credenziali utente.


. Per impostare le credenziali per l'host, attenersi alla seguente procedura:
+
.. Fare clic con il pulsante destro del mouse sull'host sotto il repository e selezionare *Open* (Apri).
.. Nella finestra host Credentials Authentication (autenticazione credenziali host), immettere le credenziali dell'utente.


. Per impostare le credenziali per il profilo, procedere come segue:
+
.. Fare clic con il pulsante destro del mouse sul profilo sotto l'host e selezionare *Open* (Apri).
.. Nella finestra Profile Credentials Authentication (autenticazione credenziali profilo), immettere le credenziali dell'utente.



