---
permalink: windows/task-clear-user-credentials-for-all-hosts-repositories-and-profiles.html 
sidebar: sidebar 
keywords: clear, cache, credential, resource, host, repository, repositories, profile, delete, authenticate, host 
summary: 'È possibile cancellare la cache delle credenziali per le risorse (host, repository e profili). In questo modo vengono eliminate tutte le credenziali delle risorse per l"utente che esegue il comando. Dopo aver cancellato la cache, è necessario autenticare nuovamente le credenziali per accedere a queste risorse protette.' 
---
= Cancella le credenziali utente per tutti gli host, i repository e i profili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile cancellare la cache delle credenziali per le risorse (host, repository e profili). In questo modo vengono eliminate tutte le credenziali delle risorse per l'utente che esegue il comando. Dopo aver cancellato la cache, è necessario autenticare nuovamente le credenziali per accedere a queste risorse protette.

.Fasi
. Per cancellare le credenziali, immettere `smsap credential clear` Dalla CLI di SnapManager oppure selezionare *Amministratore* > *credenziali* > *Cancella cache* dalla GUI di SnapManager.
. Uscire dalla GUI di SnapManager.
+
[NOTE]
====
** Se la cache delle credenziali è stata cancellata dalla GUI di SnapManager, non è necessario uscire dalla GUI di SnapManager.
** Se la cache delle credenziali è stata cancellata dall'interfaccia utente di SnapManager, è necessario riavviare l'interfaccia utente di SnapManager.
** Se il file di credenziale crittografato è stato eliminato manualmente, è necessario riavviare nuovamente l'interfaccia grafica di SnapManager.


====
. Per impostare nuovamente le credenziali, ripetere la procedura per impostare le credenziali per il repository, l'host del profilo e il profilo. Per ulteriori informazioni sulla nuova impostazione delle credenziali utente, fare riferimento a "impostazione delle credenziali dopo la cancellazione della cache delle credenziali".

