---
permalink: windows/task-clone-databases-from-backups.html 
sidebar: sidebar 
keywords: clone, database, backup, create, command 
summary: È possibile clonare un database da un backup utilizzando il comando clone create. 
---
= Clonare i database dai backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile clonare un database da un backup utilizzando `clone create` comando.



== A proposito di questa attività

Creare prima un file di specifica clone per il database. SnapManager crea il clone in base alle informazioni contenute in questo file di specifica.

Dopo aver clonato un database, è possibile aggiornare il `tnsnames.ora` file sui computer client con le nuove informazioni di connessione al database clonate. Il `tnsnames.ora` I file vengono utilizzati per connettersi a un'istanza Oracle senza dover specificare le informazioni complete del database. SnapManager non aggiorna `tnsnames.ora` file.

Se si utilizza il profilo creato con, SnapManager crea sempre un backup che include i file di log dell'archivio `-include-with-online-backups`. SnapManager consente di clonare solo i backup completi del database.

SnapManager (3.2 o versione successiva) consente di clonare i backup contenenti i file di dati e i file di log dell'archivio.

Se il log di archiviazione è disponibile da una posizione esterna, è possibile specificare la posizione esterna durante la clonazione per il ripristino del database clonato in uno stato coerente. L'utente deve assicurarsi che la posizione esterna sia accessibile da Oracle. La clonazione dei backup solo log dell'archivio non è supportata.

Sebbene il backup del registro di archiviazione venga creato insieme al backup parziale online, non è possibile creare un clone del database utilizzando questo backup.

Quando si specificano le posizioni del registro di archiviazione esterno per il ripristino del database clonato in uno stato coerente, è necessario assicurarsi di includere i nomi delle posizioni esterne in maiuscolo. Nel file system, i nomi di tutte le cartelle e sottocartelle devono essere in maiuscolo perché il database Oracle converte il percorso di destinazione in maiuscolo e prevede che i percorsi di destinazione esterni, i nomi delle cartelle e i nomi delle sottocartelle siano in maiuscolo. Se si specificano i percorsi di destinazione del log di archiviazione esterno in minuscolo, il database potrebbe non essere in grado di identificare il percorso specificato e non riuscire a ripristinare il database clonato.

È possibile clonare il backup del database dalla posizione del file di log dell'archivio esterno solo per un database standalone.

È possibile specificare `-dump` opzione come parametro opzionale per raccogliere i file dump dopo l'operazione di creazione del clone riuscita o non riuscita.

*Clonazione del backup dei file di dati senza backup del log di archiviazione*

Quando il backup dei file di dati non include il backup del registro di archiviazione, SnapManager per SAP clona il database in base al numero di modifica del sistema registrato durante il backup. Se non è possibile ripristinare il database clonato, il `Archived log file for thread <number> and change <SCN> required to complete recovery` Viene visualizzato un messaggio di errore, anche se SnapManager per SAP continua a clonare il database e alla fine riesce a creare il clone.

Quando si esegue il cloning utilizzando il backup dei file di dati senza includere il backup del registro di archiviazione, SnapManager ripristina il database clonato fino all'ultimo SCN del registro di archiviazione, registrato durante il backup.

.Fasi
. Creare un file di specifica clone.
. Per creare un clone, immettere il seguente comando:
+
`+smsap clone create-backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofile_name-clonespecfull_path_to_clonespecfile [-taskspec _taskspec_] [-recover-from-location] path1 [,<path2>...]] [-dump]+`


