---
permalink: windows/task-creating-backup-schedules.html 
sidebar: sidebar 
keywords: schedule, backup, time, frequency, suit, data, environment, creating, create 
summary: 'È possibile pianificare un backup in base all"ora e alla frequenza adatte per i dati e l"ambiente.' 
---
= Creazione di pianificazioni di backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile pianificare un backup in base all'ora e alla frequenza adatte per i dati e l'ambiente.

Da SnapManager 3.2 per SAP, è possibile pianificare i backup dei file di log dell'archivio separatamente. Tuttavia, è necessario utilizzare il profilo creato per separare i file di log dell'archivio.

Se sono stati pianificati i backup dei file di dati e dei file di registro dell'archivio contemporaneamente, SnapManager crea prima il backup dei file di dati.

Se si seleziona l'intervallo di pianificazione come -onetimonly, tutte le opzioni di eliminazione sono disponibili. Se si seleziona un intervallo di pianificazione diverso da -onetimonly, le opzioni di eliminazione -Until-SCN e -Until-date non sono supportate e viene visualizzato il seguente messaggio di errore: L'opzione di eliminazione del registro di archiviazione specificata, -Until-scn o -Until-date per l'intervallo di pianificazione orario non è valida. Specificare l'opzione -onetimeonly per l'intervallo di pianificazione oppure eseguire la riduzione dei registri di archiviazione utilizzando una qualsiasi delle opzioni all oppure -before {-months | -days | -weeks| -hours}.

Quando si verifica un failover in ambienti Microsoft Windows Server failover Cluster (WSFC) e Microsoft Cluster Server (MSCS), è necessario riavviare il server SnapManager per SAP in modo che l'indirizzo del servizio (virtuale) sia mappato all'host attivo e le pianificazioni SnapManager siano regolate sull'host SnapManager attivo.


NOTE: Se in un altro repository sono presenti lo stesso nome di profilo e pianificazione, l'operazione di pianificazione del backup non viene avviata in quel repository. L'operazione viene chiusa con il seguente messaggio: Operazione già in esecuzione.

. Immettere il seguente comando: `smsap schedule create -profile profile_name {[-full {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-data [-filesfiles [files]] | [-tablespaces-tablespaces [-tablespaces]] {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-archivelogs]} [-commentcomment][-backup-destpath1 [,[path2]] [-exclude-destpath1 [,path2]] [-prunelogs{-all | -untilSCNuntilSCN | -until-dateyyyy-MM-dd HH:mm:ss | -before {-months | -weeks | -days | -hours}} -prune-destprune_dest1,prune_dest2] -schedule-nameschedule_name [-schedule-commentschedule_comment] -interval {-hourly | -daily | -weekly | -monthly | -onetimeonly} -cronstringcronstring-start-time {start-timestart_time <yyyy-MM-dd HH:mm\>} -runasuser-runasuser [-force] [-taskspec-taskspec] [-quiet | -verbose]`
+
|===
| Se si desidera... | Quindi... 


 a| 
*Pianificare un backup di un database online o offline*
 a| 
Specificare -offline o -online per pianificare un backup del database offline o online. Se si specificano questi valori, non è possibile utilizzare -auto.



 a| 
*Lasciare che SnapManager gestisca la pianificazione di un database indipendentemente dal fatto che sia online o offline*
 a| 
Specificare -auto. Se si specifica -auto, non è possibile utilizzare --offline o -online.



 a| 
*Pianificare un backup dei file di dati*
 a| 
Specificare -data -files per elencare i file separati da virgole. Ad esempio, utilizzare i nomi dei file f1,f2,f3.



 a| 
*Pianificare un backup parziale di spazi tabella specifici*
 a| 
Specificare -tablespaces per elencare i tablespaces separati da virgole. Ad esempio, utilizzare ts1,ts2,ts3.



 a| 
*Pianificare il backup dei file di log dell'archivio*
 a| 
Specificare quanto segue:

** -archiveed per pianificare il backup dei file di log dell'archivio
** -backup-dest per pianificare le destinazioni dei file di log di archiviazione da includere nel backup
** -exclude-dest per pianificare le destinazioni del registro di archiviazione da escludere dal backup




 a| 
*Specificare i valori della classe di conservazione*
 a| 
Specificare -retain e indicare se il backup deve essere conservato in base a una delle seguenti classi di conservazione:

** orario
** giornaliero
** settimanale
** mensile
** -Unlimited SnapManager (numero illimitato): Il valore predefinito è orario.




 a| 
*Schedule pruning dei file di log di archivio*
 a| 
Specificare quanto segue: ** -Prunelogs per rimuovere i file di log dell'archivio durante la pianificazione di un backup ** -prune-dest per specificare la destinazione del log dell'archivio da cui vengono eliminati i file di log dell'archivio



 a| 
*Includere un nome per la pianificazione*
 a| 
Specificare -schedule-name.



 a| 
*Pianificare il backup del database a un intervallo di tempo specifico*
 a| 
Specificare l'opzione Interval (intervallo) e selezionare l'intervallo di tempo tra i seguenti, in base al quale creare i backup:

** orario
** giornaliero
** settimanale
** mensile
** -onetimeonly




 a| 
*Configurare una pianificazione*
 a| 
Specificare -cronstring e includere le seguenti sette sottoespressioni che descrivono la singola opzione:

** 1 si riferisce ai secondi.
** 2 indica i minuti.
** 3 si riferisce alle ore.
** 4 si riferisce a un giorno in un mese.
** 5 si riferisce al mese.
** 6 si riferisce a un giorno in una settimana.
** (Facoltativo) 7 si riferisce all'anno. *Nota:* se il backup è stato pianificato con orari diversi in -cronstring e -start-time, la pianificazione del backup viene sovrascritta e attivata da -start-time.




 a| 
*Aggiungere un commento sulla pianificazione del backup*
 a| 
Specificare -schedule-comment seguito dalla stringa di descrizione.



 a| 
*Specificare l'ora di inizio dell'operazione di pianificazione*
 a| 
Specificare -start-time nel formato yyyy-mm-gg hh:mm.



 a| 
*Modificare l'utente dell'operazione di backup pianificata durante la pianificazione del backup*
 a| 
Specificare -runasuser. L'operazione viene eseguita come utente (utente root o utente Oracle) che ha creato la pianificazione. Tuttavia, è possibile utilizzare il proprio ID utente, se si dispone di credenziali valide sia per il profilo del database che per l'host.



 a| 
*Attivare un'attività di pre-task o post-task dell'operazione di pianificazione del backup utilizzando il file XML delle specifiche di pre-task e post-task*
 a| 
Specificare l'opzione -taskspec e fornire il percorso assoluto del file XML delle specifiche delle attività per eseguire una pre-elaborazione o un'attività di post-elaborazione prima o dopo l'operazione di pianificazione del backup.

|===

