---
permalink: windows/task-adding-new-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, profile, command, add 
summary: Dopo aver configurato una notifica e-mail di riepilogo per il database del repository, è possibile aggiungere un nuovo profilo alla notifica di riepilogo utilizzando il comando di notifica di riepilogo. 
---
= Aggiunta di un nuovo profilo alle notifiche email di riepilogo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato una notifica e-mail di riepilogo per il database del repository, è possibile aggiungere un nuovo profilo alla notifica di riepilogo utilizzando il comando di notifica di riepilogo.

. Immettere il seguente comando: `smsap profile create -profileprofile_name [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | \{-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly-countn] [-durationm]] [-daily-countn] [-durationm]] [-weekly-countn] [-durationm]] [-monthly-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][ [ ]] [-summary-notification]`
+
Le altre opzioni per questo comando sono le seguenti:

+
[-force] (forza)


