---
permalink: windows/task-cloning-databases-from-backups.html 
sidebar: sidebar 
keywords: clone, database, backup, create, command, cloning 
summary: È possibile clonare un database da un backup utilizzando il comando clone create. 
---
= Clonare i database dai backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile clonare un database da un backup utilizzando il comando clone create.

Creare prima un file di specifica clone per il database. SnapManager crea il clone in base alle informazioni contenute in questo file di specifica.

Dopo aver clonato un database, è possibile aggiornare i file tnsname.ora sui computer client con le nuove informazioni di connessione al database clonato. I file tnsnames.ora vengono utilizzati per connettersi a un'istanza Oracle senza dover specificare le informazioni complete del database. SnapManager non aggiorna i file tnsnames.ora.

Se si utilizza il profilo creato con -include-with-online-backups, SnapManager crea sempre un backup che include i file di log dell'archivio. SnapManager consente di clonare solo i backup completi del database.

SnapManager (3.2 o versione successiva) consente di clonare i backup contenenti i file di dati e i file di log dell'archivio.

Se il log di archiviazione è disponibile da una posizione esterna, è possibile specificare la posizione esterna durante la clonazione per il ripristino del database clonato in uno stato coerente. L'utente deve assicurarsi che la posizione esterna sia accessibile da Oracle. La clonazione dei backup solo log dell'archivio non è supportata.

Sebbene il backup del registro di archiviazione venga creato insieme al backup parziale online, non è possibile creare un clone del database utilizzando questo backup.

Quando si specificano le posizioni del registro di archiviazione esterno per il ripristino del database clonato in uno stato coerente, è necessario assicurarsi di includere i nomi delle posizioni esterne in maiuscolo. Nel file system, i nomi di tutte le cartelle e sottocartelle devono essere in maiuscolo perché il database Oracle converte il percorso di destinazione in maiuscolo e prevede che i percorsi di destinazione esterni, i nomi delle cartelle e i nomi delle sottocartelle siano in maiuscolo. Se si specificano i percorsi di destinazione del log di archiviazione esterno in minuscolo, il database potrebbe non essere in grado di identificare il percorso specificato e non riuscire a ripristinare il database clonato.

È possibile clonare il backup del database dalla posizione del file di log dell'archivio esterno solo per un database standalone.

È possibile specificare l'opzione -dump come parametro facoltativo per raccogliere i file dump dopo l'operazione di creazione del clone riuscita o non riuscita.

*Clonazione del backup dei file di dati senza backup del log di archiviazione*

Quando il backup dei file di dati non include il backup del registro di archiviazione, SnapManager per SAP clona il database in base al numero di modifica del sistema registrato durante il backup. Se non è possibile ripristinare il database clonato, viene visualizzato il messaggio di errore file di log archiviato per thread <number> e change <SCN> required to complete recovery error, anche se SnapManager per SAP continua a clonare il database e infine riesce a creare il clone.

Quando si esegue il cloning utilizzando il backup dei file di dati senza includere il backup del registro di archiviazione, SnapManager ripristina il database clonato fino all'ultimo SCN del registro di archiviazione, registrato durante il backup.

. Creare un file di specifica clone.
. Per creare un clone, immettere il seguente comando: `+smsap clone create-backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofile_name-clonespecfull_path_to_clonespecfile [-taskspectaskspec] [-recover-from-location] path1 \[,<path2\>...\]] [-dump]+`


*Informazioni correlate*

xref:task-cloning-databases-in-the-current-state.adoc[Clonazione dei database nello stato corrente]

xref:concept-considerations-for-cloning-a-database-to-an-alternate-host.adoc[Considerazioni per clonare un database su un host alternativo]

xref:task-creating-clone-specifications.adoc[Creazione di specifiche di cloni]

xref:reference-the-smosmsapclone-create-command.adoc[Il comando di creazione del clone di smsap]

xref:task-creating-pretask-post-task-and-policy-scripts.adoc[Creazione di script di pre-task, post-task e policy]

xref:concept-variables-available-in-the-task-scripts-for-clone-operation.adoc[Variabili disponibili negli script di attività per l'operazione di cloni]

xref:task-creating-task-scripts.adoc[Creazione di script di attività]

xref:task-storing-the-task-scripts.adoc[Memorizzazione degli script delle operazioni]
