---
permalink: windows/task-create-profiles.html 
sidebar: sidebar 
keywords: create, profile, assign, oracle, database, policy, set, retention, count, class 
summary: Durante la creazione dei profili, è possibile assegnare un account utente del database Oracle specifico al profilo. È possibile impostare il criterio di conservazione per il profilo e il conteggio e la durata della conservazione per ciascuna classe di conservazione. 
---
= Creare profili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la creazione dei profili, è possibile assegnare un account utente del database Oracle specifico al profilo. È possibile impostare il criterio di conservazione per il profilo e il conteggio e la durata della conservazione per ciascuna classe di conservazione.



== A proposito di questa attività

Se non si forniscono i valori di `-login`, `-password`, e. `-port` Parametri del database, la modalità di autenticazione del sistema operativo utilizza le credenziali predefinite.

Durante la creazione di un profilo, SnapManager esegue un controllo dell'idoneità al ripristino per determinare il meccanismo di ripristino che può essere utilizzato per ripristinare il database.

SnapManager (3.2 o versione successiva) consente di separare i file di log dell'archivio dai file di dati durante la creazione di un nuovo profilo o l'aggiornamento di un profilo esistente. Dopo aver separato il backup utilizzando il profilo, è possibile creare solo il backup dei file di dati o il backup del database solo log di archiviazione. È possibile utilizzare il nuovo profilo o il profilo aggiornato per creare il backup contenente sia i file di dati che i file di log dell'archivio. Tuttavia, non è possibile utilizzare il profilo per creare il backup completo o ripristinare le impostazioni.

*Profili per la creazione di backup completi e parziali*

È possibile creare profili per creare il backup completo del database contenente i file di dati, i file di controllo e i file di log dell'archivio e il backup parziale del database contenente file di dati o tablespace specifici, tutti i file di controllo e tutti i file di log dell'archivio. SnapManager non consente di creare backup separati del registro di archiviazione utilizzando i profili creati per backup completi e parziali.

*Profili per la creazione di backup solo file di dati e backup solo archivio*

Quando si crea un nuovo profilo, è possibile includere `-separate-archivelog-backups` per separare il backup del registro di archiviazione dal backup del file di dati. È inoltre possibile aggiornare il profilo esistente per separare il backup del registro di archiviazione dal backup del file di dati.

Utilizzando le nuove opzioni del profilo per separare i backup del registro di archiviazione, è possibile eseguire le seguenti operazioni SnapManager:

* Creare un backup del registro di archiviazione
* Eliminare un backup del registro di archiviazione
* Montare un backup del registro di archiviazione
* Liberare un backup del registro di archiviazione


Durante la creazione del profilo per separare i backup del log di archiviazione dal backup dei file di dati, se i file di log di archiviazione non esistono nel database per cui è stato creato il profilo, viene visualizzato un messaggio di avviso.


WARNING: `Archived log file does not exist in the active file system. The archived log file versions earlier than the <archive log thread version> log file will not be included in the backup`

Anche se si creano backup per questo database, i file di log dell'archivio non sono disponibili nei backup del database.


NOTE: Se si verifica un errore durante la creazione di un profilo, utilizzare `smsap system dump` comando. Dopo aver creato un profilo, se si verifica un errore, utilizzare `smsap operation dump` e. `smsap profile dump` comandi.

.Fase
. Per creare un profilo con nome utente, password e porta (autenticazione Oracle), immettere il seguente comando:
+
`*smsap profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_dbname-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]][-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Le altre opzioni per questo comando sono le seguenti:

+
[`-force`] [`-noprompt`]

+
[`quiet` | `verbose`]

+
È inoltre possibile includere altre opzioni durante la creazione dei profili, a seconda di come si desidera accedere al database.

+
|===
| Se... | Quindi... 


 a| 
*Si desidera utilizzare l'autenticazione del database per creare un profilo*
 a| 
Specificare i dettagli di accesso al database.



 a| 
*Specificare un criterio di conservazione del backup per i backup*
 a| 
Specificare il numero di conservazione o la durata di una classe di conservazione o entrambi. La durata è espressa in unità della classe (ad esempio, ore per ora, giorni per giorno).

** `-hourly` è la classe di conservazione oraria per la quale [`-count n`] [`-duration m`] sono rispettivamente il numero di conservazione e la durata della conservazione.
** `-daily` è la classe di conservazione giornaliera per cui [`-count n`] [`-duration m`] sono rispettivamente il numero di conservazione e la durata della conservazione.
** `-weekly` è la classe di conservazione settimanale, per cui [`-count n`] [`-duration m`] sono rispettivamente il numero di conservazione e la durata della conservazione.
** `-monthly` è la classe di conservazione mensile, per cui [`-count n`] [`-duration m`] sono rispettivamente il numero di conservazione e la durata della conservazione.




 a| 
*Si desidera attivare la notifica via email per lo stato di completamento delle operazioni del database*
 a| 
Specificare le seguenti opzioni e variabili:

** `-summary-notification` consente di configurare una notifica email di riepilogo per più profili in un database repository.
** `-notification` consente di ricevere una notifica via email per lo stato di completamento dell'operazione del database per un profilo.
** `-success-emailemail_address2` consente di ricevere una notifica via email sull'operazione di database eseguita correttamente utilizzando un profilo nuovo o esistente.
** `-failure-emailemail_address2` consente di ricevere una notifica via email sull'operazione di database non riuscita eseguita utilizzando un profilo nuovo o esistente.
** `-subjectsubject_text` specifica il testo dell'oggetto della notifica e-mail durante la creazione di un nuovo profilo o di un profilo esistente. Se le impostazioni di notifica non sono configurate per il repository e si tenta di configurare le notifiche di profilo o di riepilogo utilizzando la CLI, il seguente messaggio viene registrato nel log della console: `SMSAP-14577: Notification Settings not configured`.
+
Se sono state configurate le impostazioni di notifica e si tenta di configurare la notifica di riepilogo utilizzando l'interfaccia CLI senza attivare la notifica di riepilogo per il repository, nel log della console viene visualizzato il seguente messaggio: `SMSAP-14575: Summary notification configuration not available for this repository`





 a| 
*Si desidera eseguire il backup dei file di log dell'archivio separatamente dai file di dati*
 a| 
Specificare le seguenti opzioni e variabili:

** `-separate-archivelog-backups` consente di separare il backup del registro di archiviazione dal backup del file di dati.
** `-retain-archivelog-backups` imposta la durata della conservazione per i backup del registro di archiviazione. Specificare una durata di conservazione positiva.
+
I backup del registro di archiviazione vengono conservati in base alla durata della conservazione del registro di archiviazione. I backup dei file di dati vengono conservati in base alle policy di conservazione esistenti.

** `-include-with-online-backups` include il backup del registro di archiviazione e il backup del database online.
+
Questa opzione consente di creare insieme un backup dei file di dati online e un backup dei registri di archiviazione per la clonazione. Quando questa opzione è impostata, ogni volta che si crea un backup dei file di dati online, i backup dei registri dell'archivio vengono creati immediatamente insieme ai file di dati.

** `-no-include-with-online-backups` non include il backup del registro di archiviazione insieme al backup del database.




 a| 
*È possibile raccogliere i file dump dopo l'operazione di creazione del profilo riuscita*
 a| 
Specificare `-dump` alla fine di `profile create` comando.

|===

