---
permalink: windows/task-configuring-e-mail-notification-for-an-existing-profile.html 
sidebar: sidebar 
keywords: updating, update, profile, configure, receive, email, notification, completion, database, operation, configuring, exist 
summary: 'Quando si aggiorna un profilo, è possibile configurare per ricevere una notifica via email al completamento dell"operazione del database.' 
---
= Configurazione della notifica e-mail per un profilo esistente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si aggiorna un profilo, è possibile configurare per ricevere una notifica via email al completamento dell'operazione del database.

* È necessario configurare l'indirizzo e-mail da cui vengono inviati gli avvisi.
* È necessario inserire un singolo indirizzo e-mail o più indirizzi e-mail a cui verranno inviati gli avvisi.
+
È possibile utilizzare un elenco separato da virgole per più indirizzi. Assicurarsi che non vi sia spazio tra la virgola e l'indirizzo e-mail successivo. In alternativa, è possibile aggiungere un oggetto all'e-mail.

+

NOTE: Assicurarsi di inserire il set di indirizzi e-mail multipli tra virgolette doppie.



.Fase
. Immettere il seguente comando:
+
`smsap profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password db_password-port db_port]] [{-rman{-controlfile | {-login  -usernamerman_username-password  rman_password-tnsname  rman_tnsname}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][[ [ ]]| [[]] [-notification [-success-emailemail_address1,email_address2-subjectsubject_pattern] [-failure-emailemail_address1,email_address2-subjectsubject_pattern]]`

+
È possibile utilizzare l'opzione Success per ricevere una notifica solo per le operazioni di database riuscite e l'opzione failure per ricevere una notifica solo per le operazioni di database non riuscite.


