---
permalink: windows/task-update-target-database-hostname-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, sap, provide, ability, update, host, name, target, database, profile, associate 
summary: 'SnapManager (3.2 o versione successiva) per SAP consente di aggiornare il nome host del database di destinazione nel profilo SnapManager.' 
---
= Aggiornare il nome host del database di destinazione associato a un profilo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager (3.2 o versione successiva) per SAP consente di aggiornare il nome host del database di destinazione nel profilo SnapManager.



== Di cosa hai bisogno

* La home directory dell'utente locale deve essere consapevole delle mappature da profilo a repository.
* Le sessioni dell'interfaccia grafica utente (GUI) di SnapManager devono essere chiuse.




== A proposito di questa attività

È possibile aggiornare il profilo con il nuovo nome host utilizzando solo l'interfaccia CLI.

*Scenari non supportati per la modifica del nome host del database di destinazione nel profilo*

I seguenti scenari non sono supportati per la modifica del nome host del database di destinazione nel profilo:

* Modifica del nome host del database di destinazione mediante l'interfaccia grafica di SnapManager
* Eseguire il rollback del database del repository dopo aver aggiornato il nome host del database di destinazione del profilo
* Aggiornamento di più profili per un nuovo nome host del database di destinazione mediante un singolo comando
* Modifica del nome host del database di destinazione quando è in esecuzione un'operazione SnapManager



NOTE: Dopo aver aggiornato il nome host del database di destinazione nel profilo, viene modificato solo il nome host del database di destinazione. Tutti gli altri parametri di configurazione impostati sul profilo vengono conservati.

Dopo aver aggiornato il nome host del database di destinazione, non è possibile eliminare o smontare il backup se il clone o il backup montato non sono disponibili nel nuovo host. In tali scenari, l'esecuzione delle operazioni SnapManager dal nuovo host comporta errori e voci obsolete nell'host precedente. Per eseguire operazioni SnapManager, è necessario ripristinare il nome host precedente utilizzando `profile update`.

.Fasi
. Immettere il seguente comando:
+
`*smsap profile update -profile _profile_ [-profile-password _profile_password_][-database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_]] [{-rman{-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_}}} | -remove-rman] [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-summary-notification] [-notification [-success -email _email_address1_, _email_address2_ -subject _subject_pattern_] [-failure -email _email_address1_, _email_address2_ -subject _subject_pattern_]] [-separate-archivelog-backups-retain-archivelog-backups -hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_ [-protect [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Le altre opzioni per questo comando sono le seguenti:

+
[`-force`] [`-noprompt`]

+
[`quiet` | `-verbose`]

+
|===
| Se si desidera... | Quindi... 


 a| 
*Modificare il nome host del database di destinazione*
 a| 
Specificare `-host _new_db_host_`

|===
. Per visualizzare il nome host del database di destinazione del profilo, immettere il seguente comando:
+
`smsap profile show`


