---
permalink: unix-administration/concept-variables-available-in-the-task-scripts-for-clone-operation.html 
sidebar: sidebar 
keywords: snapmanager, environment, variable, clone, operation, script, host, database, backup 
summary: 'SnapManager fornisce informazioni di contesto sotto forma di variabili di ambiente correlate all"operazione di cloni eseguita. Ad esempio, lo script può recuperare il nome dell"host originale, il nome del database clone e l"etichetta del backup.' 
---
= Variabili disponibili negli script di attività per l'operazione di cloni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager fornisce informazioni di contesto sotto forma di variabili di ambiente correlate all'operazione di cloni eseguita. Ad esempio, lo script può recuperare il nome dell'host originale, il nome del database clone e l'etichetta del backup.

La tabella seguente elenca le variabili di ambiente che è possibile utilizzare negli script:

|===
| Variabili | Descrizione | Formato 


 a| 
`_SM_ORIGINAL_SID_`
 a| 
SID del database originale
 a| 
stringa



 a| 
`_SM_ORIGINAL_HOST_`
 a| 
Nome host associato al database originale
 a| 
stringa



 a| 
`_SM_ORIGINAL_OS_USER_`
 a| 
Proprietario del sistema operativo del database originale
 a| 
stringa



 a| 
`_SM_ORIGINAL_OS_GROUP_`
 a| 
Gruppo di sistemi operativi del database originale
 a| 
stringa



 a| 
`_SM_TARGET_SID_`
 a| 
SID del database clone
 a| 
stringa



 a| 
`_SM_TARGET_HOST_`
 a| 
Nome host associato al database clone
 a| 
stringa



 a| 
`_SM_TARGET_OS_USER_`
 a| 
Proprietario del sistema operativo del database clone
 a| 
stringa



 a| 
`_SM_TARGET_OS_GROUP_`
 a| 
Gruppo di sistemi operativi del database clone
 a| 
stringa



 a| 
`_SM_TARGET_DB_PORT_`
 a| 
Porta del database di destinazione
 a| 
intero



 a| 
`_SM_TARGET_GLOBAL_DB_NAME_`
 a| 
Nome del database globale del database di destinazione
 a| 
stringa



 a| 
`_SM_BACKUP_LABEL_`
 a| 
Etichetta del backup utilizzato per il clone
 a| 
stringa

|===