---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: 'È possibile gestire la sicurezza in SnapManager applicando l"autenticazione dell"utente e il RBAC (role-based access control). Il metodo di autenticazione dell"utente consente di accedere a risorse come repository, host e profili. RBAC consente di limitare le operazioni che SnapManager può eseguire rispetto ai volumi e alle LUN contenenti i file di dati nel database.' 
---
= Sicurezza e gestione delle credenziali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire la sicurezza in SnapManager applicando autenticazione dell'utente e RBAC (role-based access control). Il metodo di autenticazione dell'utente consente di accedere a risorse come repository, host e profili. RBAC consente di limitare le operazioni che SnapManager può eseguire rispetto ai volumi e alle LUN contenenti i file di dati nel database.

Quando si esegue un'operazione utilizzando l'interfaccia della riga di comando (CLI) o l'interfaccia utente grafica (GUI), SnapManager recupera il set di credenziali per repository e profili. SnapManager salva le credenziali delle installazioni precedenti.

Il repository e i profili possono essere protetti con una password. Una credenziale è la password configurata per l'utente per un oggetto e la password non è configurata sull'oggetto stesso.

È possibile gestire l'autenticazione e le credenziali eseguendo le seguenti operazioni:

* Gestire l'autenticazione dell'utente tramite richieste di password sulle operazioni o utilizzando `smsap credential set` comando.
+
Impostare le credenziali per un repository, un host o un profilo.

* Visualizzare le credenziali che regolano le risorse a cui si ha accesso.
* Cancellare le credenziali di un utente per tutte le risorse (host, repository e profili).
* Eliminare le credenziali di un utente per le singole risorse (host, repository e profili).


È possibile gestire l'accesso in base al ruolo eseguendo le seguenti operazioni:

* Abilitare RBAC per SnapManager utilizzando SnapDrive.
* Assegnare gli utenti ai ruoli e impostare le funzionalità dei ruoli utilizzando la console di Operations Manager.
* Facoltativamente, abilitare SnapManager per memorizzare le password crittografate modificando `smsap.config file`.


Se Protection Manager è installato, l'accesso alle funzionalità è interessato nei seguenti modi:

* Se è installato Gestione protezione, quando si crea un profilo di database, SnapManager crea un dataset e inserisce nel dataset i volumi che contengono i file di database.
+
Dopo un'operazione di backup, SnapManager mantiene il contenuto del dataset sincronizzato con i file di database.

* Se Gestione protezione non è installato, SnapManager non può creare un dataset e non è possibile impostare la protezione sui profili.

