---
permalink: unix-administration/concept-database-state-needed-for-restore-process.html 
sidebar: sidebar 
keywords: state, database, restore, process, perform 
summary: Lo stato del database da ripristinare dipende dal tipo di processo di ripristino che si desidera eseguire e dal tipo di file da includere. 
---
= Stato del database necessario per il processo di ripristino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lo stato del database da ripristinare dipende dal tipo di processo di ripristino che si desidera eseguire e dal tipo di file da includere.

La tabella seguente elenca lo stato in cui il database deve essere in base all'opzione di ripristino selezionata e al tipo di file che si desidera includere nel ripristino:

[cols="1,1,1,1"]
|===
| Tipo di ripristino | File inclusi | Stato del database per questa istanza | Stato del database per un'altra istanza (solo RAC) 


.3+| Solo ripristino | File di controllo | Spegnere | Spegnere 


| File di sistema | Montare o spegnere | Montare o spegnere 


| Nessun file di sistema | Qualsiasi stato | Qualsiasi stato 


.3+| Ripristino e ripristino | File di controllo | Spegnere | Spegnere 


| File di sistema | Montare | Montare o spegnere 


| Nessun file di sistema | Montare o aprire | Qualsiasi 
|===
Lo stato del database richiesto da SnapManager per un'operazione di ripristino dipende dal tipo di ripristino eseguito (file completi, parziali o di controllo). SnapManager non sposta il database in uno stato inferiore (ad esempio, da aperto a montaggio) a meno che non sia specificata l'opzione force.

SnapManager per SAP non verifica se SAP è in esecuzione. SnapManager per SAP attende lo scadere di un timeout e quindi arresta il database, che può aggiungere un'ora di tempo di ripristino aggiuntivo.
