---
permalink: unix-administration/reference-troubleshooting-snapdrive-issues.html 
sidebar: sidebar 
keywords: common, issue, snapmanager, snapdrive, troubleshooting, product 
summary: Esistono alcuni problemi comuni che potrebbero verificarsi quando si utilizza SnapManager con i prodotti SnapDrive. 
---
= Risoluzione dei problemi di SnapDrive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esistono alcuni problemi comuni che potrebbero verificarsi quando si utilizza SnapManager con i prodotti SnapDrive.

Innanzitutto, devi determinare se il problema riguarda SnapManager per SAP o SnapDrive. Se il problema riguarda un errore SnapDrive, SnapManager per SAP visualizza un messaggio di errore simile a:

[listing]
----
SMSAP-12111: Error executing snapdrive command "<snapdrive command>": <snapdrive error>
----
Di seguito viene riportato un esempio di messaggio di errore SnapDrive dove `SMSAP-12111` Indica il numero di errore SnapManager. Il `0001-770` Lo schema di numerazione rappresenta gli errori SnapDrive per UNIX.

[listing]
----
SMSAP-12111: Error executing snapdrive command
"/usr/sbin/snapdrive snap restore -file
/mnt/pathname/ar_anzio_name_10gR2_arrac1/data/undotbs02.dbf -snapname pathname.company.com:
/vol/ar_anzio_name_10gR2_arrac1:
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0": 0001-770
Admin error: Inconsistent number of files returned when listing contents of
/vol/ar_anzio_name_10gR2_arrac1/.snapshot/
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0/data
on filer pathname.
----
Di seguito sono riportati i messaggi di errore SnapDrive per UNIX più comuni relativi al rilevamento LUN, ai problemi di configurazione e allo spazio. Se si riceve uno di questi errori, consultare il capitolo risoluzione dei problemi della _Guida amministrativa e d'installazione di SnapDrive_.

[cols="3a,1a"]
|===
| Sintomo | Spiegazione 


 a| 
``0001-136 Admin error: Unable to log on to filer: <filer> Please set user name and/or password for <filer>``
 a| 
Configurazione iniziale di SnapDrive



 a| 
`0001-382 Admin error: Multipathing rescan failed`
 a| 
Errore di rilevamento LUN



 a| 
`0001-462 Admin error: Failed to unconfigure multipathing for <LUN>: spd5: cannot stop device. Device busy.`
 a| 
Errore di rilevamento LUN



 a| 
``0001-476 Admin error: Unable to discover the device associated with ... 0001-710 Admin error: OS refresh of LUN failed ...``
 a| 
Errore di rilevamento LUN



 a| 
``0001-680 Admin error: Host OS requires an update to internal data to allow LUN creation or connection. Use 'snapdrive config prepare luns' or update this information manually...``
 a| 
Errore di rilevamento LUN



 a| 
`0001-817 Admin error: Failed to create volume clone ... : FlexClone not licensed`
 a| 
Configurazione iniziale di SnapDrive



 a| 
``0001-878 Admin error: HBA assistant not found. Commands involving LUNs should fail.``
 a| 
Errore di rilevamento LUN

|===