---
permalink: unix-administration/reference-the-smosmsapbackup-delete-command.html 
sidebar: sidebar 
keywords: run, backup, delete, command, remove, clone, fail, unlimited, basis, retention, class, smsap 
summary: È possibile eseguire il comando di eliminazione del backup per rimuovere i backup che non vengono rimossi automaticamente, ad esempio i backup utilizzati per creare un clone o i backup che non sono riusciti. È possibile eliminare i backup conservati senza limiti senza modificare la classe di conservazione. 
---
= Il comando smsap backup delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire `backup delete` comando per rimuovere i backup che non vengono rimossi automaticamente, ad esempio i backup utilizzati per creare un clone o i backup che non sono riusciti. È possibile eliminare i backup conservati senza limiti senza modificare la classe di conservazione.



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[smsap backup delete
-profile _profile_name_
[-label _label_ [-data | -archivelogs\] | [-id _guid_ | -all\]
-force
[-dump\]
[-quiet | -verbose\]]
----


== Parametri

* `*-profile _profile_name_*`
+
Specifica il database associato al backup che si desidera rimuovere. Il profilo contiene l'identificatore del database e altre informazioni del database.

* `*-id _guid_*`
+
Specifica il backup con il GUID specificato. Il GUID viene generato da SnapManager quando si crea un backup. È possibile utilizzare `smsap backup list` Per visualizzare il GUID per ciascun backup.

* `*-label _label_*`
+
Specifica il backup con l'etichetta specificata. Facoltativamente, specificare l'ambito del backup come file di dati o log di archiviazione.

* `*-data*`
+
Specifica i file di dati.

* `*-archivelogs*`
+
Specifica i file di log dell'archivio.

* `*-all*`
+
Specifica tutti i backup. Per eliminare solo i backup specificati, utilizzare `-id` oppure `-label` opzione.

* `*-dump*`
+
Raccoglie i file dump dopo un'operazione di eliminazione del backup riuscita o non riuscita.

* `*-force*`
+
Forza la rimozione del backup. SnapManager rimuove il backup anche in caso di problemi di liberare le risorse associate al backup. Ad esempio, se il backup è stato catalogato con Oracle Recovery Manager (RMAN), ma il database RMAN non esiste più, incluso `-force` Elimina il backup anche se non riesce a connettersi con RMAN.

* `*-quiet*`
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* `*-verbose*`
+
Visualizza messaggi di errore, di avviso e informativi nella console.



'''


== Esempio

Il seguente esempio elimina il backup:

[listing]
----
smsap backup delete -profile SALES1 -label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
'''