---
permalink: unix-administration/reference-the-smosmsap-notification-set-command.html 
sidebar: sidebar 
keywords: notification, set, command, configure, mail, server, smsap 
summary: Per configurare il server di posta, è possibile utilizzare il comando set di notifiche. 
---
= Il comando smsap notification set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `notification set` per configurare il server di posta.



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[smsap notification set
-sender-email _email_address_
-mailhost _mailhost_
-mailport _mailport_
[-authentication
-username _username_
-password _password_]]
pass:quotes[-repository
-dbname _repo_service_name_
-port _repo_port_]]
pass:quotes[-host _repo_host_
-login -username _repo_username_
[-quiet | -verbose]]

----


== Parametri

* `*-sender-email _email_address_*`
+
Specifica l'indirizzo e-mail del mittente da cui vengono inviati gli avvisi e-mail. Da SnapManager 3.2 per SAP, è possibile includere un trattino (-) specificando il nome di dominio dell'indirizzo e-mail. Ad esempio, è possibile specificare l'indirizzo e-mail del mittente come -sender-email07lbfmdatacenter@continental-corporation.com.

* `*-mailhost _mailhost_*`
+
Specifica il nome o l'indirizzo IP del server host che gestisce le notifiche e-mail.

* `*-mailport _mailport_*`
+
Specifica il numero di porta del server di posta.

* `*-authentication -username _username_ -password _password_*`
+
Specifica i dettagli di autenticazione per l'indirizzo e-mail. Specificare il nome utente e la password.

* `*-repository*`
+
Specifica i dettagli del database del repository.

* `*-port _repo_port_*`
+
Specifica il numero di porta TCP (Transmission Control Protocol) utilizzato per accedere al database del repository.

* `*-dbname _repo_service_name_*`
+
Specifica il nome del database del repository. È possibile utilizzare il nome globale o l'identificatore di sistema.

* `*-host _repo_host_*`
+
Specifica il nome o l'indirizzo IP dell'host in cui risiede il database del repository.

* `*-login*`
+
Specifica i dettagli di accesso al repository. Questa opzione è facoltativa. Se non viene specificato, SnapManager passa automaticamente alla modalità di connessione autenticazione del sistema operativo.

* `*-username _repo_username_*`
+
Specifica il nome utente richiesto per accedere al database del repository.

* `*-quiet*`
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* `*-verbose*`
+
Visualizza messaggi di errore, di avviso e informativi nella console.



'''


== Esempio

Nell'esempio seguente viene configurato il server di posta:

[listing]
----
smsap notification set -sender-email admin@org.com -mailhost hostname.org.com -mailport 25 authentication -username davis -password davis -repository -port 1521 -dbname SMSAPREPO -host hotspur
-login -username grabal21 -verbose
----
'''