---
permalink: unix-administration/reference-the-smosmsapprotection-policy-command.html 
sidebar: sidebar 
keywords: run, protection-policy, command, list, policies, applied, apply, profile, protection, policy, exist, update, manager, smsap 
summary: È possibile eseguire il comando Protection-policy per elencare i criteri di protezione che possono essere applicati a un profilo. Il criterio di protezione può essere applicato quando viene creato un nuovo profilo o aggiornato un profilo esistente. È inoltre possibile impostare il criterio di protezione per il profilo utilizzando la console di Protection Manager. 
---
= Il comando smsap Protection-policy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire `protection-policy` comando per elencare i criteri di protezione che possono essere applicati a un profilo. Il criterio di protezione può essere applicato quando viene creato un nuovo profilo o aggiornato un profilo esistente. È inoltre possibile impostare il criterio di protezione per il profilo utilizzando la console di Protection Manager.



== Sintassi

[listing]
----

        smsap protection-policy list
----

NOTE: Per utilizzare questo comando, è necessario che Gestione protezione e SnapDrive siano installati sul server.



== Parametri

* ``*list*``
+
Visualizza l'elenco dei criteri di protezione che è possibile impostare su un profilo.





== Esempio

Nell'esempio seguente sono elencati i criteri di protezione che è possibile impostare su un profilo:

[listing]
----
smsap protection-policy list
----
[listing]
----

Back up
Back up, then mirror
Chain of two mirrors
DR Back up
DR Back up, then mirror
DR Mirror
DR Mirror and back up
DR Mirror and mirror
DR Mirror, then back up
DR Mirror, then mirror
Local backups only
Mirror
Mirror and back up
Mirror to two destinations
Mirror, then back up
No protection
Partial-volume Mirror
Remote backups only
----