---
permalink: unix-administration/reference-how-to-locate-dump-files.html 
sidebar: sidebar 
keywords: dump, file, locate, client, system, easy, access, troubleshoot, profile, system, operation 
summary: Il file dump si trova nel sistema client per un facile accesso. Questi file sono utili per risolvere un problema relativo al profilo, al sistema o a qualsiasi operazione. 
---
= Come individuare i file dump
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il file dump si trova nel sistema client per un facile accesso. Questi file sono utili per risolvere un problema relativo al profilo, al sistema o a qualsiasi operazione.

Il file dump si trova nella home directory dell'utente sul sistema client.

* Se si utilizza l'interfaccia grafica utente (GUI), il file dump si trova in:
+
[listing]
----
user_home/Application Data/NetApp/smsap/3.3.0/smsap_dump dump_file_type_name
server_host.jar
----
* Se si utilizza l'interfaccia della riga di comando (CLI), il file dump si trova in:
+
[listing]
----
user_home/.netapp/smsap/3.3.0/smsap_dump_dump_file_type_name server_host.jar
----


Il file dump contiene l'output del comando dump. Il nome del file dipende dalle informazioni fornite. La tabella seguente mostra i tipi di operazioni di dump e i nomi dei file risultanti:

[cols="1a,4a"]
|===
| Tipo di operazione di dump | Nome file risultante 


 a| 
Comando dump dell'operazione con ID dell'operazione
 a| 
`smsap_dump_ _operation-id_.jar`



 a| 
Comando dump dell'operazione senza ID operazione
 a| 
`smsap operation dump -profile _VH1_ -verbose` Viene visualizzato il seguente output:

[listing]
----
smsap operation dump -profile VH1 -verbose
[ INFO] SMSAP-13048: Dump Operation Status: SUCCESS
[ INFO] SMSAP-13049: Elapsed Time: 0:00:01.404
Dump file created.
Path: /oracle/VH1/<path>/smsap/3.3.0/smsap_dump_VH1_kaw.rtp.foo.com.jar
----


 a| 
Comando dump del sistema
 a| 
`smsap_dump_ _host-name_.jar`



 a| 
Comando di dump del profilo
 a| 
`smsap_dump_ _profile-name_host-name_.jar`

|===