---
permalink: unix-administration/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credentials, user, access, resource, secure, host, repositories, repository, database, profile, snapmanager, run, password, smsap 
summary: 'Questo comando consente di impostare le credenziali per consentire agli utenti di accedere a risorse sicure, come host, repository e profili di database. La password host è la password dell"utente sull"host su cui è in esecuzione SnapManager. La password del repository è la password dell"utente Oracle che contiene lo schema del repository SnapManager. La password del profilo è una password creata dalla persona che crea il profilo. Per le opzioni host e repository, se l"opzione -password opzionale non è inclusa, verrà richiesto di inserire una password del tipo specificato negli argomenti del comando.' 
---
= Il comando sspap credential set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando consente di impostare le credenziali per consentire agli utenti di accedere a risorse sicure, come host, repository e profili di database. La password host è la password dell'utente sull'host su cui è in esecuzione SnapManager. La password del repository è la password dell'utente Oracle che contiene lo schema del repository SnapManager. La password del profilo è una password creata dalla persona che crea il profilo. Per le opzioni host e repository, se opzionale `-password` opzione non inclusa, verrà richiesto di inserire una password del tipo specificato negli argomenti del comando.



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[smsap credential set
[-host
-name _host_name_
-username _username_\]
[-password _password_\] \] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_\] [-password _repo_password_\] \]
-port _repo_port_ |
[-profile
-name _profile_name_\]
[-password _password_\] \]
[-quiet | -verbose]]
----


== Parametri

* `*-host _hostname_*`
+
Specifica il nome o l'indirizzo IP del server host su cui è in esecuzione SnapManager.

+
Il `-host` il parametro include le seguenti opzioni:

+
** `-name _host_name_`: Specifica il nome dell'host per il quale si desidera impostare la password.
** `-username _user_name_`: Specifica il nome utente sull'host.
** `-password _password_` Specifica la password dell'utente sull'host.


* `*-repository -dbname*`
+
Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.

+
Il `-repository` il parametro include le seguenti opzioni:

+
** `-dbname _repo_service_name_`: Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.
** `-host _repo_host_`: Specifica il nome o l'indirizzo IP del server host su cui viene eseguito il database del repository.
** `-login-username _repo_username_`: Specifica il nome utente necessario per accedere al database in cui è memorizzato il repository.
** `-password _password_`: Specifica la password necessaria per accedere al database che memorizza il repository.
** `-port _repo_port_`: Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.


* `*-profile -name _profile_name_*`
+
Specifica il profilo a cui è associato il database.

+
Il `-profile` il parametro include la seguente opzione:

+
** `-name _profilename_`: Specifica il nome del profilo per il quale si desidera impostare la password.
** `-password _password_`: Specifica la password necessaria per accedere al profilo.


* `*-quiet*`
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* `*-verbose*`
+
Visualizza messaggi di errore, di avviso e informativi sulla console.



'''


== Esempio di comando per l'impostazione delle credenziali del repository

Nell'esempio seguente vengono impostate le credenziali per un repository.

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----
'''
'''


== Esempio di comando per l'impostazione delle credenziali dell'host

Poiché una credenziale host rappresenta una credenziale effettiva del sistema operativo, deve includere il nome utente oltre alla password.

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
'''