---
permalink: unix-administration/reference-the-smo-notification-removesummarynotification-command.html 
sidebar: sidebar 
keywords: command, disable, summary, notification, profile, repository, database, smsap, remove-summary-notification 
summary: Questo comando disattiva la notifica di riepilogo per più profili in un database repository. 
---
= Il comando sspap notification remove-summary-notification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando disattiva la notifica di riepilogo per più profili in un database repository.



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[smsap notification remove-summary-notification
-repository
-dbname _repo_service_name_
-port _repo_port_
-host _repo_host_
-login -username _repo_username_
[-quiet | -verbose]]
----


== Parametri

* `*-repository*`
+
Le opzioni seguenti `-repository` specificare i dettagli del database per il repository.

* `*-port _repo_port_*`
+
Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.

* `*-dbname _repo_service_name_*`
+
Specifica il nome del database in cui è memorizzato il repository. Utilizzare il nome globale o il SID.

* `*-host _repo_host_*`
+
Specifica il nome o l'indirizzo IP del computer host su cui viene eseguito il database del repository.

* `*-login _repo_username_*`
+
Specifica il nome di accesso necessario per accedere al database in cui è memorizzato il repository.

* `*-quiet*`
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* `*-verbose*`
+
Visualizza messaggi di errore, di avviso e informativi sulla console.



'''
Nell'esempio seguente viene disattivata la notifica di riepilogo per più profili in un database di repository.

[listing, subs="+macros"]
----
pass:quotes[smsap notification remove-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login -username oba5]
----
'''