---
permalink: unix-administration/reference-the-smosmsap-history-list-command.html 
sidebar: sidebar 
keywords: command, enable, view, list, history, details, snapmanager, operation, smsap 
summary: 'Questo comando consente di visualizzare un elenco dei dettagli della cronologia dell"operazione SnapManager.' 
---
= Il comando ssap history list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando consente di visualizzare un elenco dei dettagli della cronologia dell'operazione SnapManager.



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[smsap history list
-profile {-name _profile_name_ [_profile_name1, profile_name2_\] | -all
-repository -login [-password _repo_password_\] -username _repo_username_
-host _repo_host_
-dbname _repo_dbname_
-port _repo_port_}
-operation {-operations _operation_name_ [_operation_name1, operation_name2_\] | -all}
[-delimiter _character_\] [-quiet | -verbose\]]
----


== Parametri

* `*-profile _profile_*`
+
Specifica il nome del profilo. Questo nome può contenere fino a 30 caratteri e deve essere univoco all'interno dell'host.

* `*_-repository_*`
+
Le opzioni che seguono -repository specificano i dettagli del database che memorizza il profilo.

* `*-dbname _repo_dbname_*`
+
Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.

* `*-host _repo_host_*`
+
Specifica il nome o l'indirizzo IP del computer host su cui viene eseguito il database del repository.

* `*-login*`
+
Avvia i dettagli di accesso al repository.

* `*-username _repo_username_*`
+
Specifica il nome utente necessario per accedere al database in cui è memorizzato il repository.

* `*-port _repo_port_*`
+
Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.

* `*-operation {-operations _operation_name_ [_operation_name1, operation_name2_] | -all*`
+
Specifica l'operazione SnapManager per la quale si configura la cronologia.

* `*-quiet*`
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* `*-verbose*`
+
Visualizza messaggi di errore, di avviso e informativi sulla console.



'''


== Esempio di comando

[listing]
----
 smsap history list -profile -name PROFILE1 -operation -operations backup -verbose
----
'''