---
permalink: unix-administration/reference-the-smosmsap-operation-show-command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, output, client, user, snapmanager, host, smsap 
summary: 'È possibile eseguire il comando show dell"operazione per elencare le informazioni di riepilogo di tutte le operazioni eseguite rispetto al profilo specificato. L"output elenca l"utente client (l"utente per il PC client) e l"utente effettivo (l"utente in SnapManager valido sull"host selezionato).' 
---
= Il comando show dell'operazione sspap
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il comando show dell'operazione per elencare le informazioni di riepilogo di tutte le operazioni eseguite rispetto al profilo specificato. L'output elenca l'utente client (l'utente per il PC client) e l'utente effettivo (l'utente in SnapManager valido sull'host selezionato).



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[smsap operation show
-profile _profile_name_
[-label _label_ | -id _id_\] [-quiet | -verbose\]]
----


== Parametri

* `*-profile _profile_name_*`
+
Specifica il nome del profilo. Questo nome può contenere fino a 30 caratteri e deve essere univoco all'interno dell'host.

* `*-label _label_*`
+
Specifica l'etichetta per l'operazione.

* `*-id _id_*`
+
Specifica l'identificativo dell'operazione.

* `*-quiet*`
+
Facoltativo: Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* `*-verbose*`
+
Facoltativo: Visualizza messaggi di errore, di avviso e informativi nella console.



'''


== Esempio

La seguente riga di comando mostra informazioni dettagliate su un'operazione:

[listing]
----
smsap operation show -id 8ac861781d0ac992011d0ac999680001  -profile CER
----
[listing]
----
Operation Attempted
    Operation ID: 8ac861781d0ac992011d0ac999680001
    Type:Backup
    For profile: CER
    With Force: No
    Label: 081017180043
    Comments: BRBACKUP
Operation Runtime Information
   Status: SUCCESS
   Start date: 2008-10-16 18:01:00 IST
   End date: 2008-10-17 18:01:26 IST
   Client user: oracle
   Effective user: oracle
   By schedule: none
Host
   Host Run upon: lnx225-248.lab.eng.org.com
   Process ID: 29096
   SnapManager version: 3.3
Repository
   Connection: krishna@smsaprep/10.72.225.155:1521
   Repository version: 62
Error messages
   The operation did not generate any error messages.
Resources in use
   Snapshots:
      f270-225-57:/vol/f270_lnx225_248_10gr2_sap_oracle_cer:smsap_cer_cer1_f_c_2_8ac861781d0ac992011d0ac999680001_0
   Storage components:
    /sapbackup/backCER1.log (File)
    /sapbackup/bdzbalta.anf (File)
    /sapreorg/spaceCER1.log (File)
    /mnt/oracle/CER (File System)
    ...
----
'''