---
permalink: unix-administration/reference-mounting-a-flexclone-fails-in-nfs-environment.html 
sidebar: sidebar 
keywords: snapmanager, create, flexclone, volume, nfs, environment, export, file, clone, backup, fail, mount, error, message 
summary: Quando SnapManager crea un FlexClone di un volume in un ambiente NFS, viene aggiunta una voce nel file /etc/exports. Impossibile montare il clone o il backup su un host SnapManager con un messaggio di errore. 
---
= Il montaggio di un volume FlexClone non riesce in ambiente NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando SnapManager crea un FlexClone di un volume in un ambiente NFS, viene aggiunta una voce in `/etc/exports` file. Impossibile montare il clone o il backup su un host SnapManager con un messaggio di errore.

Il messaggio di errore è: `0001-034 Command error: mount failed: mount: filer1:/vol/SnapManager_20090914112850837_vol14 on /opt/NTAPsmsap/mnt/-ora_data02-20090914112850735_1 - WARNING unknown option "zone=vol14" nfs mount: filer1:/vol/SnapManager_20090914112850837_vol14: Permission denied`.

Contemporaneamente, nella console del sistema di storage viene generato il seguente messaggio: `Mon Sep 14 23:58:37 PDT [filer1: export.auto.update.disabled: warning]: /etc/exports was not updated for vol14 when the vol clone create command was run. Please either manually update /etc/exports or copy /etc/exports.new to it`.

Questo messaggio potrebbe non essere acquisito nei messaggi AutoSupport.


NOTE: Potrebbero verificarsi problemi simili durante la clonazione di volumi FlexVol su NFS. Per attivare, seguire la stessa procedura `nfs.export.auto-update` opzione.

*Cosa fare*

. Impostare `nfs.export.auto-update` opzione `_on_` in modo che il `/etc/exports` il file viene aggiornato automaticamente.


`*options nfs.export.auto-update _on_*`


NOTE: Nella configurazione ha Pair, assicurarsi di impostare l'opzione NFS exports (esportazioni NFS) su on per entrambi i sistemi storage.
