---
permalink: unix-administration/reference-the-smosmsapclone-delete-command.html 
sidebar: sidebar 
keywords: run, clone, delete, command, operation, smsap 
summary: 'È possibile eseguire il comando di eliminazione dei cloni per eliminare un clone. Non è possibile eliminare un clone se utilizzato da un"operazione.' 
---
= Il comando di eliminazione del clone di smsap
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire `clone delete` per eliminare un clone. Non è possibile eliminare un clone se utilizzato da un'operazione.



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[smsap clone delete
-profile _profile_name_
[-id _guid_ | -label _clone_name_\]
[-login
[-username _db_username_ -password _db_password_ -port _db_port_\]
[-asminstance -asmusername _asminstance_username_ -asmpassword _asminstance_password_\]]]
[-syspassword _syspassword_] -force
[-dump] [-quiet | -verbose]

----


== Parametri

* ``*-profile _profile_name_*``
+
Specifica il nome del profilo contenente il clone da eliminare. Il profilo contiene l'identificatore del database e altre informazioni del database.

* ``*-force*``
+
Elimina il clone anche se sono presenti risorse associate al clone.

* ``*-id _guid_*``
+
Specifica il GUID per il clone da eliminare. Il GUID viene generato da SnapManager quando si crea un clone. È possibile utilizzare `smsap clone list` Per visualizzare il GUID per ciascun clone.

* ``*-label _name_*``
+
Specifica l'etichetta per il clone da eliminare.

* ``*-asminstance*``
+
Specifica le credenziali utilizzate per accedere all'istanza di Automatic Storage Management (ASM).

* ``*-asmusername _asminstance_username_*``
+
Specifica il nome utente utilizzato per accedere all'istanza di ASM.

* ``*-asmpassword _asminstance_password_*``
+
Specifica la password utilizzata per accedere all'istanza di ASM.

* ``*-syspassword _syspassword_*``
+
Specifica la password per l'utente con privilegi sys.

+

NOTE: È necessario fornire la password per l'utente con privilegi di sistema se le credenziali del database fornite non sono le stesse per l'utente con privilegi di sistema.

* ``*-login*``
+
Consente di immettere i dettagli di accesso al database.

* ``*-username _db_username_*``
+
Specifica il nome utente richiesto per accedere al database.

* ``*-password _db_password_*``
+
Specifica la password richiesta per accedere al database.

* ``*-port _db_port_*``
+
Specifica il numero di porta TCP utilizzato per accedere al database descritto dal profilo.

* ``*-dump*``
+
Specifica di raccogliere i file dump dopo l'operazione di eliminazione del clone.

* ``*-quiet*``
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* ``*-verbose*``
+
Visualizza messaggi di errore, di avviso e informativi nella console.



'''


== Esempio

Il seguente esempio elimina il clone:

[listing]
----
smsap clone delete -profile SALES1 -label SALES_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
'''