---
permalink: unix-administration/task-configure-history-for-backup-operation.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, maintain, history, cli, gui, history, configuring, configure, operation, report 
summary: 'SnapManager per SAP consente di mantenere la cronologia delle operazioni SnapManager dalla CLI o dall"interfaccia grafica utente di SnapManager. È possibile visualizzare la cronologia dell"operazione SnapManager come report.' 
---
= Configurare la cronologia per il funzionamento di SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager per SAP consente di mantenere la cronologia delle operazioni SnapManager dalla CLI o dall'interfaccia grafica utente di SnapManager. È possibile visualizzare la cronologia dell'operazione SnapManager come report.

.Fase
. Per configurare la cronologia delle operazioni SnapManager, immettere il seguente comando:
+
`*smsap history set -profile _{-name, profile_name_ [_profile_name1, profile_name2_] | _-all_ -repository -login [-password _repo_password_] -username _repo_username_ -dbname _repo_dbname_ -host _repo_host_ -port _repo_port_} -operation {-operations _operation_name_ [_-operation_name1, operation_name2_] | -all} -retain {-count _retain_count_ | -daily _retain_daily_ | -weekly _retain_weekly_ | -monthly _retain_monthly_} [-quiet | -verbose]*`



'''
[listing]
----

smsap
history set -profile -name PROFILE1 -operation -operations backup -retain -daily 6 -verbose
----
[listing]
----

smsap
history set -profile -name PROFILE1 -operation -all -retain -weekly 3 -verbose
----
'''