---
permalink: unix-administration/task-reset-profile-password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember, provide 
summary: È possibile reimpostare la password del profilo se non si ricorda la password fornita durante la creazione del profilo. 
---
= Reimpostare la password del profilo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile reimpostare la password del profilo se non si ricorda la password fornita durante la creazione del profilo.

*Cosa ti serve*

* Assicurarsi che il server SnapManager sia in esecuzione nel database del repository.
* È necessario disporre delle credenziali utente root dell'host su cui risiede il database del repository.
* È necessario assicurarsi che il profilo non sia in uso per alcuna operazione quando si ripristina la password per tale profilo.


*A proposito di questa attività*

È possibile reimpostare la password dall'interfaccia utente di SnapManager o dalla GUI. Durante la reimpostazione della password, SnapManager interroga il server SnapManager sull'host del repository per identificare il sistema operativo per l'host del repository. Immettere le credenziali dell'utente autorizzato per la connessione all'host del repository. Il server SnapManager autentica gli utenti con le proprie credenziali root nel database del repository. Una volta completata l'autenticazione, SnapManager ripristina la password del profilo sul server SnapManager con la nuova password.


NOTE: SnapManager non mantiene la cronologia delle operazioni di reimpostazione della password.

.Fase
. Reimpostare la password del profilo immettendo il seguente comando:
+
`*smsap password reset -profile _profile_ [-profile-password _profile_password_] [-repository-hostadmin-password _admin_password_]*`


