---
permalink: unix-administration/task-update-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, database, operating, system, os, authentication, updating, information, host, database, oracle, updating 
summary: 'È possibile aggiornare i profili per modificare la password del profilo, il numero di backup da conservare, l"accesso al database, l"autenticazione del sistema operativo per l"autenticazione del database e viceversa e le informazioni sull"host. Se le informazioni relative alla password del database Oracle cambiano, è necessario modificarle anche nel profilo.' 
---
= Aggiornare i profili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare i profili per modificare la password del profilo, il numero di backup da conservare, l'accesso al database, l'autenticazione del sistema operativo per l'autenticazione del database e viceversa e le informazioni sull'host. Se le informazioni relative alla password del database Oracle cambiano, è necessario modificarle anche nel profilo.

*A proposito di questa attività*

Se il criterio di protezione è attivato nel profilo, non è possibile modificarlo utilizzando SnapManager. L'amministratore dello storage deve modificare il criterio utilizzando la console di Protection Manager.

SnapManager (3.2 o versione successiva) consente di aggiornare il profilo per separare i backup del registro di archiviazione dai backup del file di dati utilizzando `-separate-archivelog-backups` opzione. È possibile specificare una durata di conservazione separata e un criterio di protezione per il backup del registro di archiviazione. SnapManager consente di includere il backup del registro di archiviazione insieme al backup del database online. È inoltre possibile creare un backup dei file di dati online e un backup dei log di archiviazione per la clonazione. Quando si crea un backup dei file di dati online, i backup dei registri di archiviazione vengono creati immediatamente insieme ai file di dati.

.Fasi
. Immettere il seguente comando:
+
`*smsap profile update -profile _profile_ [-new-profile _new_profile_name_] [-profile-password _profile_password_][-database-dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_][-asminstance -asmusername _asminstance_username_ -asmpassword _asminstance_password_]] [{-rman{-controlfile | {-login  -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_}}} | -remove-rman]-osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname -pattern _pattern_][[-protect [-protection-policy _policy_name_]]| [[-noprotect]] [-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]] [-separate-archivelog-backups-retain-archivelog-backups-hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_ [-protect [-protection-policy _policy_name_] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Le altre opzioni per questo comando sono le seguenti:

+
``[-force] [-noprompt]``

+
``[-quiet | verbose]``

+
[cols="2a,4a"]
|===
| Se si desidera... | Quindi... 


 a| 
*Modificare il profilo per utilizzare l'autenticazione del sistema operativo*
 a| 
Invece di aggiungere il nome utente, la password e la porta, specificare quanto segue:

** `-osaccount _account_name_` come nome dell'account del sistema operativo
** `-osgroup _osgroup_` Come gruppo associato all'account del sistema operativo, in genere l'account utilizzato per installare Oracle




 a| 
*Utilizzare l'autenticazione dell'istanza di Automatic Storage Management (ASM) per creare il profilo*
 a| 
Specificare le credenziali per l'autenticazione dell'istanza ASM.

** `-asmusername _asminstance_username_` È il nome utente utilizzato per accedere all'istanza di ASM.
** `-asmpassword _asminstance_password_` È la password utilizzata per accedere all'istanza di ASM.




 a| 
*Utilizzare un catalogo come repository di Oracle Recovery Manager (RMAN) oppure rimuovere RMAN*
 a| 
Specificare le seguenti opzioni e variabili:

** `-tnsname _tnsname_` come nome tnsname definito in `tnsnames.ora` file.
** `-login -username _username_` Come nome utente richiesto per la connessione al catalogo RMAN.
+
Se non specificato, SnapManager utilizza le informazioni di autenticazione del sistema operativo. Non è possibile utilizzare l'autenticazione del sistema operativo con i database RAC (Real Application Clusters).

** `-password _password_` Come password RMAN richiesta per la connessione al catalogo RMAN.
** `-controlfile` Se si utilizza il file di controllo come repository RMAN.
** `-remove-rman` Per rimuovere RMAN.




 a| 
*Modificare il criterio di conservazione del backup per i backup del database nel profilo*
 a| 
Specificare il numero di conservazione o la durata di conservazione per una classe di conservazione o entrambi per modificare il criterio di conservazione. La durata è espressa in unità della classe (ad esempio, ore per ora, giorni per giorno).

** `-hourly` è la classe di conservazione oraria per la quale `[-count _n_] [-duration _m_]]` sono rispettivamente il numero di conservazione e la durata della conservazione.
** `-daily` è la classe di conservazione giornaliera per cui `[-count _n_] [-duration _m_]]` sono rispettivamente il numero di conservazione e la durata della conservazione.
** `-weekly` è la classe di conservazione settimanale, per cui `[-count _n_] [-duration _m_]]` sono rispettivamente il numero di conservazione e la durata della conservazione.
** `-monthly` è la classe di conservazione mensile, per cui `[-count _n_] [-duration _m_]]` sono rispettivamente il numero di conservazione e la durata della conservazione.




 a| 
*Disattiva la protezione del backup per il profilo*
 a| 
Specificare `-noprotect` per non proteggere i backup del database creati utilizzando il profilo. Per un profilo che aveva `-protect` enabled (attivato), se si desidera disattivare la protezione, viene visualizzato un messaggio di avviso che indica che questa azione eliminerà il dataset e non sarà possibile ripristinare o clonare i backup per questo profilo.



 a| 
*Attivare le notifiche e-mail per lo stato di completamento delle operazioni del database*
 a| 
Specificare le seguenti opzioni e variabili:

** `-summary-notification` consente di configurare una notifica email di riepilogo per più profili in un database repository.
** `-notification` consente di ricevere una notifica via email sullo stato di completamento dell'operazione del database per un profilo.
** `-success -email _email_address2_` consente di ricevere una notifica via email dopo il completamento di un'operazione di database eseguita correttamente utilizzando un profilo nuovo o esistente.
** `-failure -email _email_address2_` consente di ricevere una notifica via email su un'operazione di database non riuscita eseguita utilizzando un profilo nuovo o esistente.
** `-subject _subject_text_` specifica il testo dell'oggetto della notifica via email durante la creazione di un nuovo profilo o di un profilo esistente. Se le impostazioni di notifica non sono configurate per il repository e si sta tentando di configurare le notifiche di profilo o di riepilogo utilizzando l'interfaccia della riga di comando (CLI), il seguente messaggio viene registrato nel log della console: `SMSAP-14577: Notification Settings not configured`.
+
Se sono state configurate le impostazioni di notifica e si sta tentando di configurare la notifica di riepilogo utilizzando l'interfaccia CLI senza attivare la notifica di riepilogo per il repository, il seguente messaggio viene registrato nel log della console: `SMSAP-14575: Summary notification configuration not available for this repository`





 a| 
*Aggiornare il profilo per creare separatamente il backup dei file di log dell'archivio*
 a| 
Specificare le seguenti opzioni e variabili:

** `-separate-archivelog-backups` consente di creare un backup dei file di log dell'archivio separatamente dai file di database.
+
Dopo aver specificato questa opzione, è possibile creare un backup solo file di dati o un backup solo archivio. Impossibile creare un backup completo. Inoltre, non è possibile ripristinare le impostazioni del profilo separando il backup. SnapManager conserva i backup in base ai criteri di conservazione per i backup creati prima di eseguire il backup solo per l'archiviazione.

** `-retain-archivelog-backups` imposta la durata della conservazione per i backup del registro di archiviazione.
+

NOTE: Se si aggiorna il profilo per la prima volta, è possibile separare i backup del registro di archiviazione dal backup dei file di dati utilizzando `-separate-archivelog-backups` specificare la durata di conservazione per i backup del registro di archiviazione utilizzando `-retain-archivelog-backups` opzione. L'impostazione della durata della conservazione è facoltativa quando si aggiorna il profilo in un secondo momento.

** `-protect` Crea un dataset applicativo nel server DFM (Data Fabric Manager) e aggiunge membri correlati al database, al file di dati, ai file di controllo e ai registri di archiviazione.
+
Se il dataset esiste, viene riutilizzato quando viene creato un profilo.

** `-protection-policy` imposta il criterio di protezione sui backup del registro di archiviazione.
** `-include-with-online-backups` specifica che il backup del registro di archiviazione è incluso insieme al backup del database.
** `-no-include-with-online-backups` specifica che il backup del file di log dell'archivio non è incluso con il backup del database.




 a| 
*Modificare il nome host del database di destinazione*
 a| 
Specificare `-host _new_db_host_` per modificare il nome host del profilo.



 a| 
*Raccogliere i file dump dopo l'operazione di aggiornamento del profilo*
 a| 
Specificare `-dump` opzione.

|===
. Per visualizzare il profilo aggiornato, immettere il seguente comando: `smsap profile show`

