---
permalink: unix-administration/task-split-a-clone-on-a-primary-or-secondary-storage.html 
sidebar: sidebar 
keywords: clone, split, complete, metadata, remove, repository, primary, secondary, storage, delete, free 
summary: È possibile utilizzare il comando clone split per dividere il clone. Una volta completata la suddivisione del clone, i metadati del clone vengono rimossi dal database del repository e il backup associato al clone può essere cancellato o liberato. 
---
= Separare un clone sullo storage primario o secondario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `clone split` per dividere il clone. Una volta completata la suddivisione del clone, i metadati del clone vengono rimossi dal database del repository e il backup associato al clone può essere cancellato o liberato.

*A proposito di questa attività*

Il nuovo profilo creato dopo l'operazione di split viene utilizzato per la gestione del clone split. Il nuovo profilo sarà simile a qualsiasi altro profilo esistente in SnapManager. È possibile utilizzare questo profilo per eseguire operazioni di backup, ripristino e clonazione.

Inoltre, è possibile configurare la notifica e-mail per il nuovo profilo. Ciò consente all'amministratore del database di essere informato sullo stato dell'operazione del database eseguita utilizzando il profilo.


NOTE: SnapManager supporta l'operazione di splitting solo se eseguita su FlexClone.

Se l'operazione di divisione non riesce, viene visualizzato un messaggio di errore appropriato con il motivo del guasto. Lo stato di più operazioni viene visualizzato anche nel registro delle operazioni. Ad esempio:

[listing]
----
--[ INFO] The following operations were completed:
Clone Split : Success
Profile Create : Failed
Clone Detach : Success
----
È possibile raccogliere i file dump dopo un'operazione di suddivisione dei cloni non riuscita o riuscita.


NOTE: Dopo aver inserito `clone split` Non arrestare il server SnapManager fino all'avvio dell'operazione di suddivisione dei cloni.


NOTE: SnapManager genera il profilo anche se non si fornisce alcun valore per l'account Oracle (osaccount e osgroup).

.Fase
. Immettere il seguente comando:
+
`*smsap clone split -profile _clone-profile_ -host _hostname_ [-label _clone-label_ | -id _clone-id_]-split-label _split-operation-label_ -comment _comment_ new-profile _new-profile-name_ [-profile-password _new-profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-siddb_sid] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly-count _n_] [-duration _m_]] [-daily-count _n_] [-duration _m_]] [-weekly-count _n_] [-duration _m_]] [-monthly-count _n_] [-duration _m_]]] [-profile-comment _profile-comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] | [-noprotect]][-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-quiet | -verbose]-dump*`


