---
permalink: unix-administration/task-view-detailed-clone-information.html 
sidebar: sidebar 
keywords: view, detail, information, clone, show, command 
summary: È possibile visualizzare informazioni dettagliate su un clone specifico utilizzando il comando clone show. 
---
= Visualizza informazioni dettagliate sui cloni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni dettagliate su un clone specifico utilizzando `clone show` comando.

*A proposito di questa attività*

Il `clone show` il comando visualizza le seguenti informazioni:

* Clonare l'identificatore di sistema e l'ID clone
* Clonare lo stato dell'operazione
* Clonare la data o l'ora di inizio e di fine della creazione
* Clona etichetta
* Clonare il commento
* Etichetta e ID di backup
* Database di origine
* Ora di inizio e fine del backup
* Nome del database, tablespace e file di dati
* Nome host e file system contenenti file di dati
* Volumi del sistema di storage e copie Snapshot che eseguono il backup del clone
* Se il clone è stato creato utilizzando il backup sullo storage primario o secondario


.Fase
. Immettere il seguente comando:
+
`*smsap clone show -profile _profile_name_ [-label _label_ | -id _guid_]*`


