---
permalink: unix-administration/task-delete-clones.html 
sidebar: sidebar 
keywords: delete, clone, size, snapshot, copy, backup, guarantee, data, deleting 
summary: 'È possibile eliminare i cloni quando la dimensione della copia Snapshot raggiunge tra il 10% e il 20% del backup. Ciò garantisce inoltre che il clone disponga dei dati più aggiornati.' 
---
= Eliminare i cloni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare i cloni quando la dimensione della copia Snapshot raggiunge tra il 10% e il 20% del backup. Ciò garantisce inoltre che il clone disponga dei dati più aggiornati.

*A proposito di questa attività*

L'etichetta è l'identificatore univoco di ciascun clone di un profilo. È possibile utilizzare l'etichetta o l'ID del clone, ma non l'identificatore di sistema (SID) per eliminare il clone.


NOTE: La SID del clone e l'etichetta del clone non sono uguali.

Quando si elimina un clone, il database deve essere in esecuzione. In caso contrario, molti file e directory per il clone esistente non verranno cancellati, con conseguente maggiore lavoro prima della creazione di un altro clone.

Le directory specificate per alcuni parametri Oracle nel clone vengono distrutte quando il clone viene cancellato e devono contenere solo dati per il database clonato: Destinazioni registro archivio, background, core e destinazioni di dump utente. I file di audit non vengono cancellati.


NOTE: Non è possibile eliminare un clone quando viene utilizzato in altre operazioni.

È possibile raccogliere i file dump dopo un'operazione di eliminazione dei cloni riuscita o non riuscita.

.Fase
. Immettere il seguente comando:
+
`*smsap clone delete -profile _profile_name_ [-label _label_ | -id _guid_] [-syspassword _syspassword_]| [login-username _db_username_ -password] _db_password_ -port _db_port_] [-asminstance- asmusername _asm_username_ -asmpassword _asm_password_][-force][-dump][-quiet]|[-verbose]*`



'''


== Esempio

[listing]
----
smsap clone delete -profile targetdb1_prof1 -label sales0908_clone1
----
'''