---
permalink: unix-administration/task-add-new-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, profile, command 
summary: Dopo aver configurato una notifica e-mail di riepilogo per il database del repository, è possibile aggiungere un nuovo profilo alla notifica di riepilogo utilizzando il comando di notifica di riepilogo. 
---
= Aggiungi un nuovo profilo alle notifiche email di riepilogo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato una notifica e-mail di riepilogo per il database del repository, è possibile aggiungere un nuovo profilo alla notifica di riepilogo utilizzando il comando di notifica di riepilogo.

.Fase
. Immettere il seguente comando:
+
`*smsap profile create -profile _profile_name_ [-profile-password _profile_password_] -repository-dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-siddb_sid] [-login-username _db_username_ -password _db_password_-port _db_port_] [-rman {-controlfile | \{-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly-count _n_] [-duration _m_]] [-daily-count _n_] [-duration _m_]] [-weekly-count _n_] [-duration _m_]] [-monthly-count_n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] [-summary-notification]*`

+
Le altre opzioni per questo comando sono le seguenti:

+
``[-force]``

+
``[-quiet | -verbose]``


