---
permalink: unix-administration/task-clone-databases-from-backups.html 
sidebar: sidebar 
keywords: clone, database, backup, create, command, cloning 
summary: È possibile clonare un database da un backup utilizzando il comando clone create. 
---
= Clonare i database dai backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile clonare un database da un backup utilizzando `clone create` comando.

*A proposito di questa attività*

Creare prima un file di specifica clone per il database. SnapManager crea il clone in base alle informazioni contenute in questo file di specifica.

Dopo aver clonato un database, è possibile aggiornare il `tnsnames.ora` file sui computer client con le nuove informazioni di connessione al database clonate. Il `tnsnames.ora` I file vengono utilizzati per connettersi a un'istanza Oracle senza dover specificare le informazioni complete del database. SnapManager non aggiorna `tnsnames.ora` file.

Se si utilizza il profilo creato con, SnapManager crea sempre un backup che include i file di log dell'archivio `-include-with-online-backups`. SnapManager consente di clonare solo i backup completi del database.

SnapManager (3.2 o versione successiva) consente di clonare i backup contenenti i file di dati e i file di log dell'archivio.

Se il log di archiviazione è disponibile da una posizione esterna, è possibile specificare la posizione esterna durante la clonazione per il ripristino del database clonato in uno stato coerente. L'utente deve assicurarsi che la posizione esterna sia accessibile da Oracle. La clonazione dei backup solo log dell'archivio non è supportata.

Sebbene il backup del registro di archiviazione venga creato insieme al backup parziale online, non è possibile creare un clone del database utilizzando questo backup.

È possibile clonare il backup del database dalla posizione del file di log dell'archivio esterno solo per un database standalone.

La clonazione del backup online del database Real Application Clusters (RAC) utilizzando la posizione esterna del file di log dell'archivio non riesce a causa di un errore di ripristino. Questo perché il database Oracle non riesce a trovare e applicare i file di log dell'archivio per il ripristino dalla posizione del log dell'archivio esterno durante la clonazione del backup del database.

È possibile specificare `-dump` opzione come parametro opzionale per raccogliere i file dump dopo l'operazione di creazione del clone riuscita o non riuscita.

*Clonazione del backup dei file di dati senza backup del log di archiviazione*

Quando il backup dei file di dati non include il backup del registro di archiviazione, SnapManager per SAP clona il database in base al numero di modifica del sistema registrato durante il backup. Se non è possibile ripristinare il database clonato, il `Archived log file for thread <number> and change <SCN> required to complete recovery` Viene visualizzato un messaggio di errore, anche se SnapManager per SAP continua a clonare il database e alla fine riesce a creare il clone.

Quando si esegue il cloning utilizzando il backup dei file di dati senza includere il backup del registro di archiviazione, SnapManager ripristina il database clonato fino all'ultimo SCN del registro di archiviazione, registrato durante il backup.

.Fasi
. Creare un file di specifica clone.
. Per creare un clone, immettere il seguente comando:
+
`*smsap clone create-backup-label _backup_name_ -newsid _new_sid_ -label _clone_label_ -profile _profile_name_ -clonespec _full_path_to_clonespecfile_ [-taskspec _taskspec_] [-recover-from-location] _path1 [,<path2>...]_] [-dump]*`


