---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti SnapManager per SAP
    url: "/index.html"
  - title: Note di rilascio
    url: "/reference-releasenotes.html"
  - section: unix-installation-cmode
  - section: unix-installation-7mode
  - section: unix-administration
  - section: windows
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Panoramica del prodotto
      url: "/unix-installation-cmode/reference-smsap-isg-product-overview.html"
    - title: Note di rilascio
      url: reference-releasenotes.html
  - title: Amministrazione
    links:
    - title: Configurazione di SnapManager per UNIX
      url: "/unix-administration/concept-configuring-snapmanager-for-oraclesap.html"
    - title: Configurazione di SnapManager per Windows
      url: "/windows/concept-configuring-snapmanager-for-oraclesap.html"
  - title: Installazione e configurazione
    links:
    - title: Workflow di implementazione (7-Mode)
      url: "/unix-installation-7mode/reference-smsap-isg-deployment-workflow.html"
    - title: Workflow di implementazione (modalità cluster)
      url: "/unix-installation-cmode/reference-smsap-isg-deployment-workflow.html"
  - title: Più risorse
    links:
    - title: Supporto NetApp
      url: https://mysupport.netapp.com/site/global/dashboard
    - title: Community NetApp
      url: https://community.netapp.com/
