---
permalink: unix-installation-cmode/reference-trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: Informazioni sul marchio 
---
= Informazioni sul marchio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ, AltaVault, Arch Design, ASUP, AutoSupport, Campaign Express, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Element, Fitness, Flash Accel, Flash Cache, Flash Pool, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, Alimentato da SolidFire, GetSuccessful, Helix Design, LockVault, Gestisci ONTAP, MetroCluster, MultiStore, NetApp, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANscreen, SANshare, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot, SnapValidator, SnapVault, SolidFire, SolidFire Helix, StorageGRID, SyncMirror, Tech OnTap, Unbound Cloud e WAFL e altri nomi sono marchi commerciali o marchi registrati di NetApp, Inc., negli Stati Uniti e/o in altri paesi. Tutti gli altri marchi o prodotti sono marchi commerciali o marchi registrati dei rispettivi titolari e devono essere trattati come tali. Un elenco aggiornato dei marchi NetApp è disponibile sul Web.

http://www.netapp.com/us/legal/netapptmlist.aspx[]
