---
permalink: unix-installation-7mode/task-modify-the-backup-retention-class.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snapmanager, assign, default, backup, retention, class, exist, modify, value, requirement, modify 
summary: 'Dopo l"aggiornamento, SnapManager assegna la classe di conservazione del backup predefinita ai backup esistenti. È possibile modificare i valori predefiniti della classe di conservazione per soddisfare i requisiti di backup.' 
---
= Modificare la classe di conservazione del backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo l'aggiornamento, SnapManager assegna la classe di conservazione del backup predefinita ai backup esistenti. È possibile modificare i valori predefiniti della classe di conservazione per soddisfare i requisiti di backup.

*A proposito di questa attività*

La classe di conservazione del backup predefinita assegnata ai backup esistenti è la seguente:

[cols="2a,3a"]
|===
| Tipo di backup | Assegnazione della classe di conservazione dopo l'aggiornamento 


 a| 
I backup devono essere conservati per sempre
 a| 
Senza limiti



 a| 
Altri backup
 a| 
Ogni giorno

|===

NOTE: È possibile eliminare i backup conservati per sempre senza modificare la classe di conservazione.

Se si esegue l'aggiornamento a SnapManager 3.0 o versioni successive, ai profili esistenti viene assegnato il valore maggiore dei due seguenti valori:

* Numero di conservazione precedente per il profilo
* Valori predefiniti per il conteggio di conservazione e la durata dei backup giornalieri, come specificato in `smsap.config` file


.Fase
. Modificare i valori assegnati a. `retain.hourly.count` e. `retain.hourly.duration` in `smsap.config` file.
+
Il `smsap.config` il file si trova in `_default installation location_/properties/smsap.config`.

+
È possibile immettere i seguenti valori:

+
** retain.hourly.count = `*12*`
** retain.hourly.duration = `*2*`



