---
permalink: unix-installation-7mode/task-verify-the-oracle-listener-configuration.html 
sidebar: sidebar 
keywords: listener, client, connection, request, incoming, manage, traffic, request, database, connect, target, status, configuration, verify, oracle, configuration, listener 
summary: 'L"ascoltatore è un processo che attende le richieste di connessione del client. Riceve le richieste di connessione del client in entrata e gestisce il traffico di queste richieste verso il database. Prima di connettersi a un database di destinazione o a un"istanza del database del repository, è possibile utilizzare il comando STATUS per verificare la configurazione del listener.' 
---
= Verificare la configurazione di Oracle listener
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'ascoltatore è un processo che attende le richieste di connessione del client. Riceve le richieste di connessione del client in entrata e gestisce il traffico di queste richieste verso il database. Prima di connettersi a un database di destinazione o a un'istanza di database del repository, è possibile utilizzare `STATUS` per verificare la configurazione del listener.

*A proposito di questa attività*

Il `STATUS` il comando visualizza le informazioni di stato di base su un listener specifico, tra cui un riepilogo delle impostazioni di configurazione del listener, gli indirizzi dei protocolli di ascolto e un riepilogo dei servizi registrati con tale listener.

. Immettere il seguente comando al prompt dei comandi: `*lsnrctl STATUS*`
+
Il valore predefinito assegnato alla porta del listener è 1521.


